(use-modules (guix build utils)
	     (guix packages)
             (guix build-system trivial)
	     (gnu packages emacs)
	     (gnu packages emacs-xyz)
	     (gnu packages version-control)
             ((guix licenses) #:prefix license:))

(package
 (name "meta-emacs-guix")
 (version "0.0.1")
 (source #f)
 (build-system trivial-build-system)
 (arguments '(#:builder (begin (mkdir %output) #t)))
 (propagated-inputs
  `(("emacs" ,emacs)
    ("emacs-rainbow-delimiters" ,emacs-rainbow-delimiters)
    ("emacs-projectile" ,emacs-projectile)
    ("emacs-beginend" ,emacs-beginend)
    ("emacs-git-gutter" ,emacs-git-gutter)
    ("emacs-yasnippet" ,emacs-yasnippet)
    ("emacs-guix" ,emacs-guix)
    ("emacs-geiser" ,emacs-geiser)
    ("emacs-magit" ,emacs-magit)
    ("git" ,git)))
 (synopsis "Profile to hack on Guix")
 (home-page "https://www.gnome.org/")
 (description
  "This package provides a meta package to hack on Guix")
 (license license:gpl3+))
