protocol bgp nixosantifilter {
    local as OWNAS;
    path metric 1;
    ipv4 {
        next hop self;
        import all;
        export none;
    };
    local OWNIP;
    neighbor 192.168.0.180 as 64993;
}
