apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 39997e5b1cb2b89b800389725ca7e99724e48749
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-vm-guixsd"
        - name: RUNC_ENVIRONMENT
          value: guix
