apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 658fffc60f946c0d769ba2c5cec4a1ff12c7b6e7
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-vm-guixsd"
        - name: RUNC_ENVIRONMENT
          value: guix
