kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: example-tekton-task
spec:
  steps:
  - name: step-0
    image: busybox
    securityContext:
      hostPID: true
      privileged: true
    script: |
      echo hello from busybox
      ps axjfwwww
      echo busybox finishe
