apiVersion: batch/v1
kind: CronJob
metadata:
  name: state-to-git
spec:
  schedule: "10 15 * * *" # every day
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: kube1
