apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-build
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 05e32883f02ce18a35506d344c20b4b9af6ac93e
        - name: RUNC_MAKE_TARGET
          value: "guixsd"
