apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-build
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 2a66677b2ad8fc7960eafd8fa925e28cc956d0e0
        - name: RUNC_MAKE_TARGET
          value: "guixsd"
