apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-build
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 87d906a0aab296580e5f7300b8b5ae42a6dc44e8
        - name: RUNC_MAKE_TARGET
          value: "guixsd"
