apiVersion: v1
kind: Pod
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: runc-guix-lan-kube3
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      set -o nounset -o errexit -o pipefail -o xtrace
      exec ip netns exec guix-workstation /mnt/rootfs/entrypoint.sh
    image: harbor.home.wugi.info/library/guix-entrypoint:3f227497
    name: runc
    hostNetwork: true
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /mnt/rootfs
      name: rootfs
    - mountPath: /mnt/guix-workstation/run
      name: guix-workstation-run
      mountPropagation: HostToContainer
    - mountPath: /mnt/guix-workstation/tmp
      name: guix-workstation-tmp
    - mountPath: /var/run/netns
      name: var-run-netns
    - mountPath: /dev/tty0
      name: dev-tty9
    - mountPath: /dev/tty9
      name: dev-tty9
    - mountPath: /dev/tty12
      name: dev-tty9
  restartPolicy: Never
  tty: true
  tolerations:
  - effect: NoSchedule
    key: edge.cluster.local/not-schedulable
    operator: Equal
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - key: workstation.cluster.local
    operator: Equal
    value: 'true'
    effect: NoSchedule
  volumes:
  - hostPath:
      path: /srv/runc/guix-lan/rootfs
      type: Directory
    name: rootfs
  - hostPath:
      path: /mnt/guix-workstation/run
      type: Directory
    name: guix-workstation-run
  - hostPath:
      path: /mnt/guix-workstation/tmp
      type: Directory
    name: guix-workstation-tmp
  - hostPath:
      path: /var/run/netns
      type: Directory
    name: var-run-netns
  - hostPath:
      path: /dev/tty9
      type: CharDevice
    name: dev-tty9
