apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 01deac4a36f4c69b178770a8f0bfcc92b3d67b7d
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-vm1"
        - name: RUNC_ENVIRONMENT
          value: guix
