apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: e567223ca4b40a377a203f8f95af468a31985bc1
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-vm1"
        - name: RUNC_ENVIRONMENT
          value: guix
