apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: libvirt
nameSuffix: -kube1
resources:
- ../../base/libvirt-pod
patchesStrategicMerge:
- pod.yaml
images:
- name: harbor.home.wugi.info/library/libvirt
  newTag: 4a19c80b-1749562227
