protocol bgp antifilter0 {
    description "https://antifilter.network";
    local as OWNAS;
    ipv4 {
       next hop self;
       import filter {
           if (net = 108.156.22.0/24)
           then
               bgp_community.add((65444, 750));
           if (net = 3.164.206.0/24)
           then
               bgp_community.add((65444, 730));
           if (net = 8.47.69.4/30) || (net = 8.6.112.4/30)
           then
               # cdn.betterttv.net
               bgp_community.add((OWNAS, 1001));
           accept;
       };
       export none;
    };
    neighbor 45.148.244.55 as 65444;
    hold time 240;
    multihop;
}
