protocol bgp antifilter0 {
    description "https://antifilter.network";
    local as OWNAS;
    ipv4 {
       next hop self;
       import filter {
           bgp_next_hop = 192.168.0.1;
       };
       export none;
    };
    neighbor 45.148.244.55 as 65444;
    hold time 240;
    multihop;
}
