protocol bgp nixosgw {
      local as OWNAS;
      local 192.168.0.180;
      ipv4 {
         next hop self;
         export all;
         import none;
      };
      neighbor 192.168.0.160 as 64990;
}
