protocol bgp nixostor {
    local as OWNAS;
    ipv4 {
        table downstream_routes;
        next hop self;
        export filter {
            if (net ~ [192.168.0.1/32, 0.0.0.0/0])
            then
                bgp_community.add((0,0));
            accept;
        };
        import none;
    };
    neighbor 192.168.0.190 as 64995;
    multihop;
}
