protocol bgp nixoszapret {
      local as OWNAS;
      local 192.168.0.180;
      ipv4 {
         next hop self;
         export all;
         import none;
      };
      neighbor 192.168.0.175 as 64997;
}
