protocol bgp nixosbview {
    local as OWNAS;
    ipv4 {
        table upstream_routes;
        next hop self;
        export none;
        import filter {
            gw = 192.168.0.150;
            accept;
        };
    };
    neighbor 192.168.0.150 as 64989;
    multihop;
}
