(deftheme manoj-dark
  "Created 2017-09-30.")

(custom-theme-set-variables
 'manoj-dark
 '(company-quickhelp-color-background "black"))

(custom-theme-set-faces
 'manoj-dark
 '(font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
 '(font-lock-constant-face ((t (:foreground "LightSlateBlue" :bold t))))
 '(font-lock-preprocessor-face ((t (:foreground "CornFlowerBlue" :italic t))))
 '(font-lock-keyword-face ((t (:foreground "cyan1"))))
 '(font-lock-type-face ((t (:foreground "SteelBlue1"))))
 '(font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "Aquamarine"))))
 '(font-lock-function-name-face ((t (:foreground "mediumspringgreen" :weight bold :height 1.1))))
 '(font-lock-string-face ((t (:foreground "RosyBrown1"))))
 '(font-lock-comment-face ((t (:italic t :slant oblique :foreground "chocolate1"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "Salmon"))))
 '(font-lock-doc-face ((t (:italic t :slant oblique :foreground "LightCoral"))))
 '(font-lock-warning-face ((t (:bold t :foreground "Pink" :weight bold))))
 '(gnus-splash ((t (:foreground "#cccccc"))))
 '(gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
 '(gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
 '(gnus-summary-high-ancient ((t (:bold t :foreground "CornflowerBlue" :weight bold))))
 '(gnus-summary-high-ancient ((t (:bold t :foreground "CornflowerBlue" :weight bold))))
 '(gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
 '(gnus-summary-normal-ancient ((t (:foreground "SkyBlue"))))
 '(gnus-summary-low-ancient ((t (:italic t :foreground "LightSteelBlue" :slant italic))))
 '(gnus-summary-high-read ((t (:bold t :foreground "grey60" :weight bold))))
 '(gnus-summary-high-read ((t (:bold t :foreground "grey60" :weight bold))))
 '(gnus-summary-normal-read ((t (:foreground "grey50"))))
 '(gnus-summary-normal-read ((t (:foreground "grey50"))))
 '(gnus-summary-low-read ((t (:italic t :foreground "LightSlateGray" :slant italic))))
 '(gnus-summary-low-read ((t (:italic t :foreground "LightSlateGray" :slant italic))))
 '(gnus-summary-high-ticked ((t (:bold t :foreground "RosyBrown" :weight bold))))
 '(gnus-summary-high-ticked ((t (:bold t :foreground "RosyBrown" :weight bold))))
 '(gnus-summary-normal-ticked ((t (:foreground "LightSalmon"))))
 '(gnus-summary-normal-ticked ((t (:foreground "LightSalmon"))))
 '(gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
 '(gnus-summary-low-ticked ((t (:italic t :foreground "pink" :slant italic))))
 '(gnus-summary-high-undownloaded ((t (:bold t :foreground "ivory3" :weight bold))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
 '(gnus-summary-low-undownloaded ((t (:italic t :foreground "grey75" :slant italic :weight normal))))
 '(gnus-summary-high-unread ((t (:bold t :foreground "PaleGreen" :weight bold))))
 '(gnus-summary-high-unread ((t (:bold t :foreground "PaleGreen" :weight bold))))
 '(gnus-summary-normal-unread ((t (:foreground "YellowGreen"))))
 '(gnus-summary-normal-unread ((t (:foreground "YellowGreen"))))
 '(gnus-summary-low-unread ((t (:italic t :foreground "MediumSeaGreen" :slant italic))))
 '(gnus-summary-low-unread ((t (:italic t :foreground "MediumSeaGreen" :slant italic))))
 '(gnus-summary-selected ((t (:underline t :foreground "LemonChiffon"))))
 '(gnus-summary-selected ((t (:underline t :foreground "LemonChiffon"))))
 '(gnus-group-mail-1 ((t (:bold t :foreground "#3BFF00" :weight normal))))
 '(gnus-group-mail-1 ((t (:bold t :foreground "#3BFF00" :weight normal))))
 '(gnus-group-mail-2 ((t (:bold t :foreground "#5EFF00" :weight normal))))
 '(gnus-group-mail-2 ((t (:bold t :foreground "#5EFF00" :weight normal))))
 '(gnus-group-mail-3 ((t (:bold t :foreground "#80FF00" :weight normal))))
 '(gnus-group-mail-3 ((t (:bold t :foreground "#A1FF00" :weight normal))))
 '(gnus-group-mail-1-empty ((t (:foreground "#249900"))))
 '(gnus-group-mail-1-empty ((t (:foreground "#249900"))))
 '(gnus-group-mail-2-empty ((t (:foreground "#389900"))))
 '(gnus-group-mail-2-empty ((t (:foreground "#389900"))))
 '(gnus-group-mail-3-empty ((t (:foreground "#4D9900"))))
 '(gnus-group-mail-3-empty ((t (:foreground "#4D9900"))))
 '(gnus-group-mail-low ((t (:bold t :foreground "aquamarine2" :weight bold))))
 '(gnus-group-mail-low ((t (:bold t :foreground "aquamarine2" :weight bold))))
 '(gnus-group-mail-low-empty ((t (:foreground "aquamarine2"))))
 '(gnus-group-mail-low-empty ((t (:foreground "aquamarine2"))))
 '(gnus-group-news-1 ((t (:bold t :foreground "#8480FF" :weight bold))))
 '(gnus-group-news-1 ((t (:bold t :foreground "#8480FF" :weight bold))))
 '(gnus-group-news-2 ((t (:bold t :foreground "#8088FF" :weight bold))))
 '(gnus-group-news-2 ((t (:bold t :foreground "#8088FF" :weight bold))))
 '(gnus-group-news-3 ((t (:bold t :foreground "#8095FF" :weight bold))))
 '(gnus-group-news-3 ((t (:bold t :foreground "#8095FF" :weight bold))))
 '(gnus-group-news-4 ((t (:bold t :foreground "#80A1FF" :weight bold))))
 '(gnus-group-news-4 ((t (:bold t :foreground "#80A1FF" :weight bold))))
 '(gnus-group-news-5 ((t (:bold t :foreground "#80AEFF" :weight bold))))
 '(gnus-group-news-5 ((t (:bold t :foreground "#80AEFF" :weight bold))))
 '(gnus-group-news-6 ((t (:bold t :foreground "#80BBFF" :weight bold))))
 '(gnus-group-news-6 ((t (:bold t :foreground "#80BBFF" :weight bold))))
 '(gnus-group-news-1-empty ((t (:foreground "#524DFF"))))
 '(gnus-group-news-1-empty ((t (:foreground "#524DFF"))))
 '(gnus-group-news-2-empty ((t (:foreground "#4D58FF"))))
 '(gnus-group-news-2-empty ((t (:foreground "#4D58FF"))))
 '(gnus-group-news-3-empty ((t (:foreground "#4D6AFF"))))
 '(gnus-group-news-3-empty ((t (:foreground "#4D6AFF"))))
 '(gnus-group-news-4-empty ((t (:foreground "#4D7CFF"))))
 '(gnus-group-news-4-empty ((t (:foreground "#4D7CFF"))))
 '(gnus-group-news-5-empty ((t (:foreground "#4D8EFF"))))
 '(gnus-group-news-5-empty ((t (:foreground "#4D8EFF"))))
 '(gnus-group-news-6-empty ((t (:foreground "#4DA0FF"))))
 '(gnus-group-news-6-empty ((t (:foreground "#4DA0FF"))))
 '(gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
 '(gnus-group-news-low ((t (:bold t :foreground "DarkTurquoise" :weight bold))))
 '(gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
 '(gnus-group-news-low-empty ((t (:foreground "DarkTurquoise"))))
 '(message-cited-text ((t (:foreground "red3"))))
 '(message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
 '(message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
 '(message-header-name ((t (:foreground "green"))))
 '(message-header-name ((t (:foreground "green"))))
 '(message-header-newsgroups ((t (:italic t :bold t :foreground "papaya whip" :slant italic :weight bold))))
 '(message-header-newsgroups ((t (:italic t :bold t :foreground "papaya whip" :slant italic :weight bold))))
 '(message-header-other ((t (:foreground "ivory"))))
 '(message-header-other ((t (:foreground "ivory"))))
 '(message-header-subject ((t (:foreground "OliveDrab1"))))
 '(message-header-subject ((t (:foreground "OliveDrab1"))))
 '(message-header-to ((t (:bold t :foreground "floral white" :weight bold))))
 '(message-header-to ((t (:bold t :foreground "floral white" :weight bold))))
 '(message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
 '(message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
 '(message-mml ((t (:foreground "MediumSpringGreen"))))
 '(message-mml ((t (:foreground "MediumSpringGreen"))))
 '(message-separator ((t (:foreground "LightSkyBlue1"))))
 '(message-separator ((t (:foreground "LightSkyBlue1"))))
 '(org-agenda-date ((t (:foreground "LightSkyBlue"))))
 '(org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
 '(org-agenda-restriction-lock ((t (:background "skyblue4"))))
 '(org-agenda-structure ((t (:foreground "LightSkyBlue"))))
 '(org-archived ((t (:foreground "grey70"))))
 '(org-code ((t (:foreground "grey70"))))
 '(org-column ((t (:background "grey30" :slant normal :weight normal :height 81))))
 '(org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
 '(org-date ((t (:foreground "Cyan" :underline t))))
 '(org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
 '(org-drawer ((t (:foreground "LightSkyBlue"))))
 '(org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
 '(org-formula ((t (:foreground "chocolate1"))))
 '(org-headline-done ((t (:foreground "LightSalmon"))))
 '(org-hide ((t (:foreground "black"))))
 '(org-level-1 ((t (:foreground "LightSkyBlue"))))
 '(org-level-2 ((t (:foreground "LightGoldenrod"))))
 '(org-level-3 ((t (:foreground "Cyan1"))))
 '(org-level-4 ((t (:foreground "chocolate1"))))
 '(org-level-5 ((t (:foreground "PaleGreen"))))
 '(org-level-6 ((t (:foreground "Aquamarine"))))
 '(org-level-7 ((t (:foreground "LightSteelBlue"))))
 '(org-level-8 ((t (:foreground "LightSalmon"))))
 '(org-link ((t (:foreground "Cyan" :underline t))))
 '(org-mode-line-clock ((t (:foreground "DarkGreen" :underline t))))
 '(org-scheduled-previously ((t (:foreground "chocolate1"))))
 '(org-scheduled-today ((t (:foreground "PaleGreen"))))
 '(org-sexp-date ((t (:foreground "Cyan"))))
 '(org-special-keyword ((t (:foreground "LightSalmon"))))
 '(org-table ((t (:foreground "LightSkyBlue"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-target ((t (:underline t))))
 '(org-time-grid ((t (:foreground "LightGoldenrod"))))
 '(org-todo ((t (:bold t :foreground "Pink" :weight bold))))
 '(org-upcoming-deadline ((t (:foreground "chocolate1"))))
 '(org-verbatim ((t (:foreground "grey70" :underline t))))
 '(org-warning ((t (:bold t :weight bold :foreground "Pink"))))
 '(outline-1 ((t (:foreground "LightSkyBlue"))))
 '(outline-2 ((t (:foreground "LightGoldenrod"))))
 '(outline-3 ((t (:foreground "Cyan1"))))
 '(outline-4 ((t (:foreground "chocolate1"))))
 '(outline-5 ((t (:foreground "PaleGreen"))))
 '(outline-6 ((t (:foreground "Aquamarine"))))
 '(outline-7 ((t (:foreground "LightSteelBlue"))))
 '(outline-8 ((t (:foreground "LightSalmon"))))
 '(bold ((t (:bold t :weight bold))))
 '(bold-italic ((t (:bold t :italic t :slant italic :weight bold))))
 '(border ((t (:background "gold" :foreground "black"))))
 '(buffer-menu-buffer ((t (:bold t :weight bold))))
 '(button ((t (:underline t :box (:line-width 2 :color "grey" :style released-button) :foreground "black" :background "grey" :weight bold))))
 '(comint-highlight-input ((t (:bold t :weight bold))))
 '(comint-highlight-prompt ((t (:foreground "cyan1"))))
 '(compilation-column-number ((t (:foreground "PaleGreen"))))
 '(compilation-error ((t (:bold t :weight bold :foreground "Brown1"))))
 '(compilation-info ((t (:bold t :foreground "LightPink1" :weight bold))))
 '(compilation-line-number ((t (:foreground "LightGoldenrod"))))
 '(compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
 '(completions-common-part ((t (:width normal :weight normal :slant normal :foreground "WhiteSmoke" :background "black" :height 81))))
 '(completions-first-difference ((t (:bold t :weight bold))))
 '(cursor ((t (:background "orchid"))))
 '(diary ((t (:foreground "IndianRed"))))
 '(diff-added ((t (:foreground "Green"))))
 '(diff-file-header ((t (:bold t :background "grey20" :foreground "ivory1" :weight bold))))
 '(diff-hunk-header ((t (:slant italic :background "DodgerBlue4"))))
 '(diff-nonexistent ((t (:bold t :weight bold :background "Black" :foreground "Wheat1"))))
 '(diff-removed ((t (:foreground "salmon1"))))
 '(eldoc-highlight-function-argument ((t (:bold t :weight bold))))
 '(epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
 '(epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(epa-mark ((t (:bold t :foreground "orange" :weight bold))))
 '(epa-string ((t (:foreground "lightyellow"))))
 '(epa-validity-disabled ((t (:italic t :slant italic))))
 '(epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
 '(epa-validity-low ((t (:italic t :slant italic))))
 '(epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
 '(escape-glyph ((t (:foreground "cyan"))))
 '(homoglyph ((t (:foreground "cyan"))))
 '(file-name-shadow ((t (:foreground "grey70"))))
 '(fringe ((t (:background "grey30" :foreground "Wheat"))))
 '(header-line ((t (:box (:line-width -1 :color "grey20" :style released-button) :background "grey20" :foreground "grey90" :height 0.9))))
 '(help-argument-name ((t (:italic t :slant italic))))
 '(highlight ((t (:background "gray10" :foreground "Old Lace"))))
 '(hl-line ((t (:background "grey10" :foreground "Old Lace"))))
 '(holiday ((t (:background "chocolate4"))))
 '(ido-first-match ((t (:bold t :weight bold))))
 '(ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Pink"))))
 '(ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
 '(ido-only-match ((t (:foreground "ForestGreen"))))
 '(ido-subdir ((t (:foreground "red1"))))
 '(info-menu-header ((t (:bold t :weight bold))))
 '(info-node ((t (:bold t :italic t :foreground "yellow"))))
 '(info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
 '(info-xref ((t (:bold t :foreground "DodgerBlue1"))))
 '(info-xref ((t (:bold t :foreground "cyan" :weight bold))))
 '(isearch ((t (:background "palevioletred2" :foreground "brown4"))))
 '(isearch-fail ((t (:background "red4"))))
 '(italic ((t (:italic t))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(link ((t (:foreground "cyan1" :underline t))))
 '(link-visited ((t (:underline t :foreground "violet"))))
 '(match ((t (:background "RoyalBlue3"))))
 '(minibuffer-prompt ((t (:foreground "cyan"))))
 '(mode-line ((t (:background "grey75" :foreground "Blue" :box (quote (:line-width -1 :style released-button)) :height 0.9))))
 '(mode-line-buffer-id ((t (:background "grey65" :foreground "red" :bold t :weight bold :height 0.9))))
 '(mode-line-emphasis ((t (:bold t :weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button :height 0.9)))))
 '(mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (quote (:line-width -1 :color "grey40")) :weight light :height 0.9))))
 '(mouse ((t (:background "OrangeRed"))))
 '(next-error ((t (:background "blue3"))))
 '(nobreak-space ((t (:foreground "cyan" :underline t))))
 '(query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
 '(region ((t (:background "blue3"))))
 '(scroll-bar ((t (:background "grey75" :foreground "WhiteSmoke"))))
 '(secondary-selection ((t (:background "SkyBlue4"))))
 '(semantic-highlight-edits-face ((t (:background "gray20"))))
 '(semantic-unmatched-syntax-face ((t (:underline "red"))))
 '(shadow ((t (:foreground "grey70"))))
 '(show-paren-match ((t (:background "steelblue3"))))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(smerge-base ((t (:foreground "orange"))))
 '(smerge-markers ((t (:background "grey30"))))
 '(smerge-upper ((t (:foreground "cyan"))))
 '(smerge-lower ((t (:foreground "lightgreen"))))
 '(smerge-refined-changed ((t (:background "blue4"))))
 '(speedbar-button-face ((t (:foreground "green3"))))
 '(speedbar-directory-face ((t (:foreground "light blue"))))
 '(speedbar-file-face ((t (:foreground "cyan"))))
 '(speedbar-highlight-face ((t (:background "sea green"))))
 '(speedbar-selected-face ((t (:foreground "red" :underline t))))
 '(speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
 '(speedbar-tag-face ((t (:foreground "yellow"))))
 '(table-cell ((t (:background "blue1" :foreground "gray90"))))
 '(tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
 '(tooltip ((t (:background "lightyellow" :foreground "black"))))
 '(trailing-whitespace ((t (:background "red1"))))
 '(underline ((t (:underline t))))
 '(vertical-border ((t (:background "dim gray"))))
 '(widget-button ((t (:bold t :weight bold :box (:line-width 2 :style released-button)))))
 '(widget-button-pressed ((t (:foreground "red1" :background "lightgrey" :box (:line-width 2 :style pressed-button)))))
 '(widget-documentation ((t (:foreground "lime green"))))
 '(widget-field ((t (:background "dim gray"))))
 '(widget-inactive ((t (:foreground "grey70"))))
 '(widget-single-line-field ((t (:background "dim gray"))))
 '(default ((t (:background "black" :foreground "WhiteSmoke")))))

(provide-theme 'manoj-dark)
