apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: searxng
resources:
- ../../base/searxng
patchesStrategicMerge:
- release.yaml
configMapGenerator:
- name: searxng-values-cluster1
  files:
  - values.yaml=values.yaml
