apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-reconfigure
  annotations:
    # Setting spec.force to true will make Flux recreate the Job when any
    # immutable field is changed, forcing the Job to run every time the
    # container image tag changes.
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  backoffLimit: 0
  template:
    spec:
      hostNetwork: true
      hostPID: true
      restartPolicy: Never
      containers:
      - image: harbor.home.wugi.info/library/util-linux-with-udev:44cd2b5c
        name: refresh
        resources:
          limits:
            cpu: 14000m
            memory: 4096Mi
          requests:
            cpu: 1000m
            memory: 512Mi
        securityContext:
          privileged: true
        command:
        - /bin/guile
        - --no-auto-compile
        - -c
        - |
          (define %git-origin
            "https://cgit.wugi.info/git/wigust/dotfiles")

          (define (host-code)
            `(begin
               (define (git . args)
                 (apply system* (append '("guix" "shell" "git" "--" "git") args)))
               (system* "/usr/bin/env")
               (and=>
                (getenv "HOME")
                (lambda (home)
                  (let* ((commit ,(getenv "GIT_COMMIT"))
                         (checkouts (string-append home "/.cache/wigust/checkouts"))
                         (workdir
                          (begin
                            (system* "mkdir" "-p" checkouts)
                            (mkdtemp (string-append checkouts "/dotfiles.XXXXXXXXXX")))))
                    (chdir workdir)
                    (and
                     (zero? (git "init"))
                     (zero?
                      (git "remote" "add" "origin" ,%git-origin))
                     (zero?
                      (git "fetch" "--depth" (number->string 1) "origin" commit))
                     (zero? (git "checkout" commit))
                     (zero?
                      (system*
                       "guix" "system" "reconfigure"
                       "--load-path=."
                       (string-append "--expression="
                                      ,(and=> (getenv "GUIX_SYSTEM")
                                              (lambda (system-name)
                                                (with-output-to-string
                                                  (lambda ()
                                                    (write
                                                     `(@ (wugi system ,system-name) ,(symbol-append '% system-name)))))))))))))))

          (define (guile-with-environment expression)
            `(let* ((user (getpw (getuid)))
                    (name (passwd:name user))
                    (shell (passwd:shell user)))
               (execl shell shell "--login" "-c"
                      (with-output-to-string
                        (lambda ()
                          (write
                           (list
                            "/run/current-system/profile/bin/guile" "--no-auto-compile"
                            "-c" ,(with-output-to-string
                                    (lambda ()
                                      (write expression))))))))))

          (apply system*
                 `("nsenter"
                   ,(string-append "--target=" (number->string 1))
                   "--mount"
                   "--uts"
                   "--ipc"
                   "--net"
                   "--pid"
                   "--no-fork"
                   ,@(or (and=> (getenv "NSENTER_UID")
                                (lambda (uid)
                                  (list (string-append "--setuid=" uid))))
                         '())
                   ,@(or (and=> (getenv "NSENTER_GID")
                                (lambda (gid)
                                  (list (string-append "--setgid=" gid))))
                         '())
                   "/run/current-system/profile/bin/guile" "--no-auto-compile"
                   "-c" ,(with-output-to-string
                           (lambda ()
                             (write (guile-with-environment (host-code)))))))
