apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 566405a99f98f05ab4cd246895b0f8a4259e6a0f
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-pc0"
        - name: RUNC_ENVIRONMENT
          value: guix
