apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 51423ce38bc7f1be5f9d9f8b69887fabba13362b
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-pc0"
        - name: RUNC_ENVIRONMENT
          value: guix
