apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: ec5d35a9a3c9d954000b38f5657c8425bc5a36f6
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-pc0"
        - name: RUNC_ENVIRONMENT
          value: guix
