apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 6410a8bcfbed248fd95b0f1278a93893acc4d549
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-image-docker-image"
        - name: RUNC_ENVIRONMENT
          value: guix
