apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 9fc666258a81b331f06add6f8371a8de55829a38
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-image-docker-image"
        - name: RUNC_ENVIRONMENT
          value: guix
