apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guix
nameSuffix: -guix-time-machine-system-image-docker-image
resources:
- ../../base/invoke-runc
patchesStrategicMerge:
- job.yaml
