{
 "title": "restic",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Restic Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "last_over_time(restic_stats_latest_total_size[9h])",
     "legendFormat": "{{ target }}@{{ job }}"
    }
   ]
  },
  {
   "title": "Restic Number of Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(restic_stats_latest_total_nfiles[9h])",
     "legendFormat": "{{ target }}@{{ job }}"
    }
   ]
  },
  {
   "title": "Restic Size Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(last_over_time(restic_stats_latest_total_size[9h]))"
    }
   ]
  },
  {
   "title": "Restic Number of Files Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(last_over_time(restic_stats_latest_total_nfiles[9h]))"
    }
   ]
  }
 ]
}