(define-module (wugi manifests obs)
  #:use-module (gnu packages video)
  #:use-module (guix channels)
  #:use-module (guix inferior)
  #:use-module (guix profiles)
  #:use-module (guix store)
  #:use-module (ice-9 match)
  #:use-module (srfi srfi-1)
  #:use-module (wugi utils)
  #:export (%obs-manifest))

(define (%obs-manifest)
  (packages->manifest (list obs)))
