;; GuixSD configuration file for the desktop machine.
;; Copyright © 2024, 2025, 2026 Oleg Pykhalov <go.wigust@gmail.com>
;; Released under the GNU GPLv3 or any later version.

(define-module (wugi manifests workstation)
  #:use-module (srfi srfi-26)
  #:use-module (wugi manifests wm)
  #:use-module (wugi utils)
  #:use-module (wugi manifests ai)
  #:use-module (wugi manifests deprecated)
  #:use-module (wugi manifests desktop)
  #:use-module (wugi manifests emacs)
  #:use-module (wugi manifests firejail)
  #:use-module (wugi manifests guile)
  #:use-module (wugi manifests icons)
  #:use-module (wugi manifests majordomo)
  #:use-module (wugi manifests nonguix)
  #:use-module (wugi manifests mqtt)
  #:use-module (wugi manifests notebook-packages)
  #:use-module (wugi manifests obs)
  #:use-module (wugi manifests pc0-packages)
  #:use-module (wugi manifests telegram)
  #:use-module (wugi manifests web)
  #:export (%workstation-manifest))

(define (%workstation-manifest)
  (combined-manifest-from-files
   (list (%pc0-packages-manifest)
         (%desktop-manifest)
         (%nonguix-manifest)
         ;; (%icons-manifest)
         (%emacs-manifest)
         ;; (%deprecated-manifest)
         ;; (%telegram-manifest)
         ;; (%majordomo-manifest)
         (%notebook-packages-manifest)
         (%obs-manifest)
         ;; (%ai-manifest)
         ;; (%firejail-manifest)
         (%guile-manifest)
         ;; (%mqtt-manifest)
         (%wm-manifest)
         (%web-manifest))))

(%workstation-manifest)
