apiVersion: batch/v1
kind: Job
metadata:
  name: nix-container-systemd
spec:
  template:
    metadata:
      annotations:
        guix-default-channel-commit: 5d9802fb
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
