apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 177ee02aa70339dd5a36f047885f69d02d415d93
        - name: RUNC_MAKE_TARGET
          value: "container-systemd-taskexecutor"
        - name: RUNC_CONTAINER_ID
          value: nix-builder
        - name: KUBERNETES_POD_NAME
          value: runc-kube1-nix-builder
        - name: KUBERNETES_NAMESPACE
          value: nix
        - name: RUNC_GUILE
          value: /etc/profiles/per-user/oleg/bin/guile
        - name: RUNC_ENVIRONMENT
          value: nix
