apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 51c66f9337e8c413d244d6f7568c9221b44b17e3
        - name: RUNC_MAKE_TARGET
          value: "container-systemd-taskexecutor"
        - name: RUNC_CONTAINER_ID
          value: nix-builder
        - name: KUBERNETES_POD_NAME
          value: runc-kube1-nix-builder
        - name: KUBERNETES_NAMESPACE
          value: nix
        - name: RUNC_GUILE
          value: /etc/profiles/per-user/oleg/bin/guile
