(("Default" 2 T NIL :CLASS "Firefox") ("Default" 2 T NIL :CLASS "IceCat")
 ("Default" 3 NIL NIL :TITLE "youtube-dl")
 ("Default" 0 NIL T :CLASS "mpv" :TITLE "emacs-emms")
 ("Default" 0 NIL NIL :CLASS "mpv") ("youtube" 0 T NIL :CLASS "mpv")
 ("youtube" 2 T NIL :CLASS "Firefox") ("youtube" 3 T NIL :CLASS "XTerm"))