apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-task-success
spec:
  interval: 10m
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.prometheus-blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - https://gitlab.corp1.majordomo.ru/
