apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-task-success-0
spec:
  interval: 10m
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.prometheus-blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - https://gitlab.corp1.majordomo.ru/

      - https://grafana.corp1.majordomo.ru/
      - https://prometheus.corp1.majordomo.ru/status
      - https://harbor.corp1.majordomo.ru/

      - https://grafana.corp2.majordomo.ru/
      - https://prometheus.corp2.majordomo.ru/status
      - https://harbor.corp2.majordomo.ru/
---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: probe-task-success-1
spec:
  interval: 60m
  module: http_2xx
  prober:
    url: prometheus-blackbox-exporter.prometheus-blackbox-exporter:9115
  targets:
    staticConfig:
      static:
      - https://ci.guix.gnu.org/
      - https://bordeaux.guix.gnu.org/
      - https://mirrors.sjtug.sjtu.edu.cn/guix/
      - https://substitutes.nonguix.org/

      - https://cache.nixos.org/

      - https://github.com/
      - https://about.gitlab.com/
      - https://codeberg.org/
