#!/usr/bin/env bash

set -eux

account="$1"
host="$2"

curl --request POST https://api.majordomo.ru/account/"$account"/transfer \
     --header "Authorization: Bearer $(mjru-auth)" \
     --header 'Content-Type: application/json' \
     --data-binary '{"operationIdentity":null,"params":{"serverId":"'"$host"'" }}'
