(in-package :stumpwm)

(mapcar (lambda (func)
          (add-hook *start-hook* func))
        (list (lambda () (sb-thread:make-thread
                     (lambda ()
                       (sleep 5)
                       (place-existing-windows)
                       (run-commands "fselect 2")
                       (run-shell-command (concat (getenv "HOME") "/bin/run-emacs")))))
              (lambda () (quassel-monitor))
              (lambda () (music-youtube))
              (lambda () (clipmenud))
              (lambda () (kdeconnect-indicator))
              (lambda () (dunst))
              (lambda () (alerta-top))
              (lambda () (pulsemixer))
              (lambda () (cursor-theme))
              (lambda () (keynav))))
