log syslog all;

define OWNAS = 64993;

protocol device {
}

protocol kernel {
    ipv4 {
        import none;
        export all;
    };
}

protocol static {
    ipv4;
    route 192.168.0.1/32 via "eth0";
    route 0.0.0.0/0 recursive 192.168.0.1;

    route 192.168.0.170/32 via "eth0"; # nixos-gw
    route 192.168.0.190/32 via "eth0"; # nixos-tor
}

ipv4 table downstream_routes;

protocol pipe {
    table master4;
    peer table downstream_routes;
    export filter {
        if (net = 0.0.0.0/0)
        then
            bgp_community.add((OWNAS,0));
        accept;
    };
    import none;
};

include "/etc/bird/peers/*.conf";
