log syslog all;

define OWNAS = 64993;

protocol device {
}

protocol kernel {
    metric 0;
    ipv4 {
        import none;
        export filter {
            if (source = RTS_STATIC) then accept;
            reject;
        };
    };
}

protocol static {
    ipv4;
    route 192.168.0.0/24 via "eth0";
    route 0.0.0.0/0 recursive 192.168.0.1;

    # antifilter0 bgp_next_hop
    route 51.75.66.20/32 recursive 192.168.0.1;
}

ipv4 table upstream_routes;
ipv4 table downstream_routes;

protocol static {
    ipv4 {
        table upstream_routes;
    };
    route 192.168.0.1/32 via "eth0";
}

protocol pipe {
    table master4;
    peer table downstream_routes;
    export filter {
        if (net = 0.0.0.0/0) then {
            bgp_community.add((OWNAS,0));
            accept;
        }
        reject;
    };
    import none;
};

protocol pipe {
    table upstream_routes;
    peer table downstream_routes;
    export filter {
        # cloudflare
        if (bgp_path.last = 13335) then {
            bgp_community.add((OWNAS,13335));
            # path of exile
            # 172.65.166.147
            if (net = 172.65.160.0/20) then {
                bgp_large_community.add((OWNAS,13335,1));
            }
            # https://www.pathofexile.com/
            if (net = 104.16.16.0/20) then {
                bgp_large_community.add((OWNAS,13335,2));
            }
            # https://gitlab.com/
            if (net = 172.65.240.0/20) then {
                bgp_large_community.add((OWNAS,13335,3));
            }
            accept;
        }
        # akamai linode
        if (bgp_path.last = 63949) then {
            bgp_community.add((OWNAS,63949));
            accept;
        }
        reject;
    };
    import none;
};

include "/etc/bird/peers/*.conf";
