kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: wget
spec:
  workspaces:
  - name: data
  steps:
  - name: check-data
    image: nixery.dev/shell/wget
    script: |
      wget -O- https://www.gnu.org
