#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

/run/current-system/profile/bin/xhost +local:

if [ -e "${HOME}/.bash_profile" ]
then
    . "${HOME}/.bash_profile"
fi

"$HOME/.guix-profile/bin/xclickroot" -r xmenu.sh &
exec -a stumpwm /bin/sh --login -c '/run/current-system/profile/bin/sbcl --load /home/oleg/bin/my-stumpwm'
