apiVersion: batch/v1
kind: Job
metadata:
  name: runc-guix-builder-kubeedge-certs
spec:
  template:
    metadata:
      annotations:
        guix-default-channel-commit: 63120741
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
