apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 59a3b55c82a8e4c8221ce4499b412cbddd278ed8
        - name: RUNC_MAKE_TARGET
          value: "kubeedge-certs"
        - name: RUNC_ENVIRONMENT
          value: guix
