(use-modules (gnu))

(use-service-modules desktop dbus)
(use-package-modules suckless xdisorg)

(list (screen-locker-service slock)
      (screen-locker-service xlockmore "xlock")
      (udisks-service)
      (service upower-service-type)
      (service accountsservice-service-type)
      (service colord-service-type)
      (geoclue-service)
      (service polkit-service-type)
      (elogind-service)
      (dbus-service)
      (service ntp-service-type)
      x11-socket-directory-service)
