apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guix
resources:
- pod.yaml
configMapGenerator:
- name: guile-nsenter
  options:
    disableNameSuffixHash: true
  files:
  - guile-script.scm=rootfs/guile-nsenter
