apiVersion: v1
kind: Pod
metadata:
  name: maintenance-guix-kube3
  annotations:
    # Setting spec.force to true will make Flux recreate the Job when any
    # immutable field is changed, forcing the Job to run every time the
    # container image tag changes.
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  hostNetwork: true
  hostPID: true
  restartPolicy: Always
  nodeSelector:
    kubernetes.io/hostname: kube3
  tolerations:
    - key: workstation.cluster.local
      operator: Equal
      value: 'true'
      effect: NoSchedule
  containers:
  - command:
    - /bin/guile
    - --no-auto-compile
    - -e
    - (guile-nsenter)
    - -s
    - /usr/local/bin/guile-script.scm
    image: harbor.home.wugi.info/library/util-linux-with-udev:44cd2b5c
    name: nsenter
    env:
    - name: NSENTER_UID
      value: "0"
    - name: NSENTER_GID
      value: "0"
    - name: RUNC_GUILE
      value: /run/current-system/profile/bin/guile
    resources:
      limits:
        cpu: 14000m
        memory: 8192Mi
      requests:
        cpu: 50m
        memory: 128Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /usr/local/bin
      name: guile-nsenter
  volumes:
  - name: guile-nsenter
    configMap:
      name: guile-nsenter
