#!/run/current-system/profile/bin/guile \
--no-auto-compile -e (guile-nsenter) -s
!#

;;;; guile-nsenter --- Run nsenter
;;;; Copyright © 2025 Oleg Pykhalov <go.wigust@gmail.com>
;;;; Released under the GNU GPLv3 or any later version.

(define-module (guile-nsenter)
  #:use-module (srfi srfi-37)
  #:export (main))

;;; Commentary:
;;;
;;; DESCRIPTION
;;;
;;; Code:

(define %options
  (let ((display-and-exit-proc (lambda (msg)
                                 (lambda (opt name arg loads)
                                   (display msg) (quit)))))
    (list (option '(#\v "version") #f #f
                  (display-and-exit-proc "guile-nsenter version 0.0.1\n"))
          (option '(#\h "help") #f #f
                  (display-and-exit-proc
                   "Usage: guile-nsenter ...")))))

(define %default-options
  '())

(define (main args)
  (define opts
    (args-fold (cdr (program-arguments))
               %options
               (lambda (opt name arg loads)
                 (error "Unrecognized option `~A'" name))
               (lambda (op loads)
                 (cons op loads))
               %default-options))
  (define (invoke program . args)
    "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
    (let ((status (apply system* program args)))
      (unless (zero? status)
        (error (format #f "program ~s exited with non-zero code" program)
               status))
      #t))
  (display "kubeedge-certs starting\n")
  (mkdir "/etc/kubernetes")
  (mkdir "/etc/kubernetes/pki")
  (copy-file "/mnt/etc/kubernetes/pki/ca.crt" "/etc/kubernetes/pki/ca.crt")
  (copy-file "/mnt/etc/kubernetes/pki/ca-key.pem" "/etc/kubernetes/pki/ca.key")
  (mkdir "/etc/kubeedge")
  (invoke "/usr/local/bin/certgen.sh" "stream"))

;;; guile-nsenter ends here
