apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-guix-datavolume
spec:
  dataVolumeTemplates:
  - metadata:
      name: guix-dv
    spec:
      pvc:
        storageClassName: topolvm-provisioner-pool0
        volumeMode: Block
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 17Gi
      source:
        http:
          url: https://iso.wugi.info/guix-system-vm-image-1.5.0.x86_64-linux.raw
