apiVersion: v1
kind: Pod
metadata:
  name: runc
spec:
  nodeSelector:
    kubernetes.io/hostname: kube1
  containers:
  - name: runc
    env:
    - name: RUNC_BUNDLE
      value: /srv/runc/guix-builder
    - name: RUNC_CONTAINER_ID
      value: guix-builder
    volumeMounts:
    - mountPath: /var/run/netns/runc
      name: var-run-netns-runc
    - mountPath: /srv/runc/guix-builder
      name: runc-guix-builder
  hostNetwork: true
  volumes:
  - name: var-run-netns-runc
    hostPath:
      path: /var/run/netns/runc
      type: File
  - name: runc-guix-builder
    hostPath:
      path: /srv/runc/guix-builder
      type: Directory
