apiVersion: v1
kind: Service
metadata:
  name: runc-kube1-guix-builder
  labels:
    app.kubernetes.io/name: runc-kube1-guix-builder
    app.kubernetes.io/part-of: guix
spec:
  ports:
  - port: 5556
    protocol: TCP
    targetPort: 5556
    name: guix
  selector:
    app.kubernetes.io/name: runc-kube1-guix-builder
    app.kubernetes.io/part-of: guix
  type: ClusterIP
