apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: e772e8014efebf44c1a78c7b920363c81cdd2c3c
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-notebook"
        - name: RUNC_ENVIRONMENT
          value: guix
