apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: b35045b1728424d6304a7d8302a91ea996047ebe
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-notebook"
        - name: RUNC_ENVIRONMENT
          value: guix
