apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: ade4a42a69212cafbce02e7f30e393411fa33b22
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-notebook"
        - name: RUNC_ENVIRONMENT
          value: guix
