#!/run/current-system/profile/bin/guile \
--no-auto-compile -e (guile-nsenter) -s
!#

;;;; guile-nsenter --- Run nsenter
;;;; Copyright © 2025 Oleg Pykhalov <go.wigust@gmail.com>
;;;; Released under the GNU GPLv3 or any later version.

(define-module (guile-nsenter)
  #:use-module (srfi srfi-37)
  #:export (main))

;;; Commentary:
;;;
;;; DESCRIPTION
;;;
;;; Code:

(define %options
  (let ((display-and-exit-proc (lambda (msg)
                                 (lambda (opt name arg loads)
                                   (display msg) (quit)))))
    (list (option '(#\v "version") #f #f
                  (display-and-exit-proc "guile-nsenter version 0.0.1\n"))
          (option '(#\h "help") #f #f
                  (display-and-exit-proc
                   "Usage: guile-nsenter ...")))))

(define %default-options
  '())

(define (guile-with-environment expression)
  `(let* ((user (getpw (getuid)))
          (name (passwd:name user))
          (shell (passwd:shell user)))
     (execl shell shell "--login" "-c"
            (with-output-to-string
              (lambda ()
                (write
                 (list
                  (getenv "RUNC_GUILE") "--no-auto-compile"
                  "-c" ,(with-output-to-string
                          (lambda ()
                            (write expression))))))))))

(define %git-origin
  "https://cgit.wugi.info/git/wigust/dotfiles")

(define %git-password-store-url
  "git@cgit.wugi.info:wigust/password-store-dotfiles")

(define (runc-code)
  `(begin
     (use-modules (srfi srfi-26))
     (define (invoke program . args)
       "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
       (let ((status (apply system* program args)))
         (unless (zero? status)
           (error (format #f "program ~s exited with non-zero code" program)
                  status))
         #t))
     (define (git . args)
       (apply invoke (append '("git") args)))
     (define (guile-with-guix-environment expression)
       (invoke "guix"
               "shell" "--load-path=guix" "--development"
               (string-append
                "--expression="
                (with-output-to-string
                  (lambda ()
                    (write '(@ (wugi packages dotfiles) dotfiles-extra)))))
               "--"
               "guile" "--no-auto-compile" "-c" (with-output-to-string
                                                  (lambda ()
                                                    (write expression)))))
     (define (guile-with-nix-environment expression)
       (invoke "nix" "develop" "./nix/dotfiles#dotfiles"
               "--command"
               "guile" "--no-auto-compile" "-c" (with-output-to-string
                                                  (lambda ()
                                                    (write expression)))))
     (invoke "/usr/bin/env")
     (and=> (getenv "HOME")
            (lambda (home)
              (let* ((commit ,(getenv "GIT_COMMIT"))
                     (checkouts
                      (string-append home "/.cache/wigust/checkouts"))
                     (workdir
                      (begin
                        (invoke "mkdir" "-p" checkouts)
                        (mkdtemp
                         (string-append checkouts "/dotfiles.XXXXXXXXXX"))))
                     (password-store ".password-store"))
                (chdir workdir)
                (and
                 (git "clone" ,%git-origin ".")
                 (git "checkout" commit)

                 (invoke "mkdir" "-p" ".password-store")
                 (chdir password-store)
                 (git "init")
                 (git "submodule" "add" ,%git-password-store-url "dotfiles")
                 (chdir "..")

                 (and=> (string->symbol ,(getenv "RUNC_ENVIRONMENT"))
                        (lambda (environment)
                          (case environment
                            ((guix)
                             (guile-with-guix-environment
                              `(begin
                                 (define (invoke program . args)
                                   "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
                                   (let ((status (apply system* program args)))
                                     (unless (zero? status)
                                       (error (format #f "program ~s exited with non-zero code" program)
                                              status))
                                     #t))
                                 (invoke "./bootstrap")
                                 (invoke "./configure")
                                 (invoke
                                  "make" ,(string-append "PASSWORD_STORE=" password-store)
                                  ,,(getenv "RUNC_MAKE_TARGET")))))
                            ((nix)
                             (guile-with-nix-environment
                              `(begin
                                 (define (invoke program . args)
                                   "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
                                   (let ((status (apply system* program args)))
                                     (unless (zero? status)
                                       (error (format #f "program ~s exited with non-zero code" program)
                                              status))
                                     #t))
                                 (invoke "./bootstrap")
                                 (invoke "./configure")
                                 (invoke
                                  "make" ,(string-append "PASSWORD_STORE=" password-store)
                                  ,,(getenv "RUNC_MAKE_TARGET"))))))))))))))

(define kubectl
  "/home/oleg/.guix-profile")

(define kubeconfig
  "/home/oleg/.kube/config")

(define (kubectl-program)
  ;; TODO: Use Kubernetes HTTP API without kubectl.
  `(begin
     (define (invoke program . args)
       "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
       (let ((status (apply system* program args)))
         (unless (zero? status)
           (error (format #f "program ~s exited with non-zero code" program)
                  status))
         #t))
     (setenv "KUBECONFIG" ,kubeconfig)
     (invoke ,(string-append kubectl "/bin/kubectl")
             (string-append "--namespace=" ,(getenv "KUBERNETES_NAMESPACE"))
             "exec" "--stdin=true"
             (string-append "pod/" ,(getenv "KUBERNETES_POD_NAME")) "--"
             "runc" "exec"
             "--user" (string-append
                       ,(getenv "RUNC_UID") ":" ,(getenv "RUNC_GID"))
             "--env" (string-append "RUNC_MAKE_TARGET="
                                    ,(getenv "RUNC_MAKE_TARGET"))
             "--env" (string-append "RUNC_GUILE=" ,(getenv "RUNC_GUILE"))
             "--env" (string-append "COLUMNS=" ,(number->string 200))
             "--env" (string-append "USER=" ,(getenv "RUNC_USER"))
             "--env" (string-append "GIT_COMMIT=" ,(getenv "GIT_COMMIT"))
             ;; Add to `docker' group in nix-builder.
             "--additional-gids" ,(number->string 131)
             ,(getenv "RUNC_CONTAINER_ID")
             ,(getenv "RUNC_GUILE") "--no-auto-compile"
             "-c" ,(with-output-to-string
                     (lambda ()
                       (write
                        (guile-with-environment (runc-code))))))))

(define (main args)
  (define opts
    (args-fold (cdr (program-arguments))
               %options
               (lambda (opt name arg loads)
                 (error "Unrecognized option `~A'" name))
               (lambda (op loads)
                 (cons op loads))
               %default-options))
  (define (invoke program . args)
    "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
    (let ((status (apply system* program args)))
      (unless (zero? status)
        (error (format #f "program ~s exited with non-zero code" program)
               status))
      #t))
  (apply invoke
         `("nsenter"
           ,(string-append "--target=" (number->string 1))
           "--mount"
           "--uts"
           "--ipc"
           "--net"
           "--pid"
           "--no-fork"
           ,@(or (and=> (getenv "NSENTER_UID")
                        (lambda (uid)
                          (list (string-append "--setuid=" uid))))
                 '())
           ,@(or (and=> (getenv "NSENTER_GID")
                        (lambda (gid)
                          (list (string-append "--setgid=" gid))))
                 '())
           "/run/current-system/profile/bin/guile" "--no-auto-compile"
           "-c" ,(with-output-to-string (lambda () (write (kubectl-program)))))))

;;; guile-nsenter ends here
