---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: install/kubernetes/cilium
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: cilium
        namespace: flux-system
  interval: 15m0s
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
