apiVersion: v1
kind: Pod
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: runc-guix-wugi-kube3
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /bin/bash
    - -c
    - |
      set -o nounset -o errexit -o pipefail -o xtrace

      mount -o remount,rw /sys

      umount /sys/fs/cgroup
      mount -t cgroup2 -o rw,relatime,nsdelegate,memory_recursiveprot cgroup2 /sys/fs/cgroup

      cd /mnt/rootfs || exit 1

      mkdir put_old
      pivot_root . put_old
      exec chroot . /gnu/store/fnfh4fqwla2s1f5v152aa3rmacp93hah-boot-program /gnu/store/4yfss9a96ijfp02xymdvxscrd44cb5vw-system
    image: harbor.home.wugi.info/library/runc:c72aa8bb
    name: runc
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /mnt/rootfs
      name: rootfs
  restartPolicy: Always
  tolerations:
  - effect: NoSchedule
    key: edge.cluster.local/not-schedulable
    operator: Equal
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - key: workstation.cluster.local
    operator: Equal
    value: 'true'
    effect: NoSchedule
  volumes:
  - hostPath:
      path: /srv/runc/guix-wugi/rootfs
      type: Directory
    name: rootfs
