{
 "title": "Networking Interfaces",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "TP-Link Archer C6 bps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_bytes_total{instance=\"192.168.0.1\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_bytes_total{instance=\"192.168.0.1\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "TP-Link Archer C6 pps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_packets_total{instance=\"192.168.0.1\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_packets_total{instance=\"192.168.0.1\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "guix.wugi.info bps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_bytes_total{instance=\"192.168.0.144:9100\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_bytes_total{instance=\"192.168.0.144:9100\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "guix.wugi.info pps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_packets_total{instance=\"192.168.0.144:9100\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_packets_total{instance=\"192.168.0.144:9100\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "pc0 bps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_bytes_total{instance=\"192.168.0.192:9100\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_bytes_total{instance=\"192.168.0.192:9100\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "pc0 pps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_packets_total{instance=\"192.168.0.192:9100\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_packets_total{instance=\"192.168.0.192:9100\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "windows bps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(windows_net_bytes_received_total{instance=\"192.168.0.152:9182\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(windows_net_bytes_sent_total{instance=\"192.168.0.152:9182\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "windows pps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(windows_net_packets_received_total{instance=\"192.168.0.152:9182\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(windows_net_packets_sent_total{instance=\"192.168.0.152:9182\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "vm1.wugi.info bps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_bytes_total{instance=\"vm1.wugi.info:9100\", device=\"eth0\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_bytes_total{instance=\"vm1.wugi.info:9100\", device=\"eth0\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "vm1.wugi.info pps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_packets_total{instance=\"vm1.wugi.info:9100\", device=\"eth0\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_packets_total{instance=\"vm1.wugi.info:9100\", device=\"eth0\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "de2.g-load.eu bps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_bytes_total{instance=\"vm1.wugi.info:9100\", device=\"de2.g-load.eu\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_bytes_total{instance=\"vm1.wugi.info:9100\", device=\"de2.g-load.eu\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  },
  {
   "title": "de2.g-load.eu pps",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(device, instance) (rate(node_network_receive_packets_total{instance=\"vm1.wugi.info:9100\", device=\"de2.g-load.eu\"}[2m])) * 8",
     "legendFormat": "incoming {{device}}"
    },
    {
     "expr": "sum by(device, instance) (rate(node_network_transmit_packets_total{instance=\"vm1.wugi.info:9100\", device=\"de2.g-load.eu\"}[2m])) * 8",
     "legendFormat": "outgoing {{device}}"
    }
   ]
  }
 ]
}