apiVersion: v1
kind: Endpoints
metadata:
  name: workstation-kube1
  labels:
    app.kubernetes.io/name: workstation-kube1
    app.kubernetes.io/part-of: workstation
subsets:
- addresses:
  - ip: 192.168.0.191
  ports:
  - port: 9091
    name: qbittorent
