apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 2d284f78074ad858e0697899444e56d53de7c250
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-vm1"
        - name: RUNC_ENVIRONMENT
          value: guix
