protocol bgp nixostor {
    local as OWNAS;
    path metric 1;
    local 192.168.0.195;
    ipv4 {
       next hop self;
       import filter {
           if (net = 0.0.0.0/0)
           then
               reject;
           # Amazon
           # Amazon CloudFront
           if (65444,750) ~ bgp_community || (65444,730) ~ bgp_community
           then
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           # адреса сетей российского сегмента.
           if (65444,643) ~ bgp_community
           then
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           accept;
       };
       export none;
    };
    neighbor 192.168.0.190 as 64995;
}
