protocol bgp nixoszapret {
    local as OWNAS;
    path metric 1;
    local 192.168.0.195;
    ipv4 {
       next hop address 192.168.0.195;
       export none;
       import filter {
           if (net = 0.0.0.0/0)
           then
               reject;
           # youtube
           if (65444,770) ~ bgp_community
           then
               accept;
           else
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           accept;
       };
    };
    neighbor 192.168.0.175 as 64997;
}
