protocol bgp r1 from dnpeers {
      # My side Tunnel IPv4
      local 192.168.0.195;
      ipv4 {
         next hop address 192.168.0.195;
      };

      # container-systemd-nixos-workstation-pc0 Side IPv4 and AS-Number
      neighbor 192.168.0.175 as 64997;
}
