apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-build
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: a87fa1dbe99ed14c02bec0591f5a968ec26c760b
        - name: RUNC_MAKE_TARGET
          value: "guix-image-workstation"
