apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-build
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: d2d8c1aec7e343c2b34d64ec2b88e2c14e917405
        - name: RUNC_MAKE_TARGET
          value: "guix-image-workstation"
