apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-build
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: bedeaaeb30b2f8d08feadf51048e5322018db7be
        - name: RUNC_MAKE_TARGET
          value: "guix-image-workstation"
