apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: vdo-ninja-cert
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - vdo.home.wugi.info
