apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-blackbox-exporter
resources:
- ../../base/prometheus-blackbox-exporter
patchesStrategicMerge:
- release.yaml
configMapGenerator:
- name: prometheus-blackbox-exporter-values-cluster1
  files:
  - values.yaml=values.yaml
