apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 4a19c80b4af3cbf59ea47e3d675f905093effa7d
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-image-libvirt"
        - name: RUNC_ENVIRONMENT
          value: guix
