apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: e4bce5af104a4bf305fc72ee23fa101abccb375c
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-image-libvirt"
        - name: RUNC_ENVIRONMENT
          value: guix
