apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: e524480571d16e6cef3a09c4d91b0ff1cfdf9f25
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-home-build-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
