apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 186021c3ba795ecd10a4bd0001e20845d4f45000
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-home-build-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
