apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 9138b971d23365c82cf1294d7bf4dfb475e196e3
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-home-build-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
