protocol bgp nixosantifilter {
    local as OWNAS;
    ipv4 {
        table upstream_routes;
        next hop self;
        import all;
        export none;
    };
    neighbor 192.168.0.180 as 64993;
    multihop;
}

