apiVersion: batch/v1
kind: Job
metadata:
  name: guix-checkout
spec:
  template:
    spec:
      containers:
      - name: nsenter
        env:
        - name: POD_NAMESPACE
          value: workstation
        - name: POD_NAME
          value: workstation-kube3
      nodeSelector:
        kubernetes.io/hostname: kube3
      tolerations:
      - key: workstation.cluster.local
        operator: Equal
        value: 'true'
        effect: NoSchedule
