log syslog all;

define OWNAS = 64979;

protocol device {
}

protocol kernel {
    learn;
    ipv4 {
        import filter {
            if net ~ [192.168.0.0/24+] then reject;
            if net ~ [192.168.0.0/16+, 172.16.0.0/12+, 78.108.80.0/24+, 78.108.88.0/23, 178.208.86.0/24, 178.250.246.0/23, 185.10.184.0/22] then accept;
            reject;
        };
        export filter {
            if (source = RTS_STATIC) && (net = 192.168.0.115/32) then accept;
            if (source = RTS_STATIC) && (net ~ [192.168.0.110/32]) then accept;
            if (source = RTS_STATIC) && (net ~ [172.16.102.35/32, 172.16.103.131/32, 172.16.103.2/32, 78.108.80.1/32, 78.108.88.1/32]) then accept;
            if (source = RTS_STATIC) && (net ~ [78.108.87.250/32]) then accept;
            if (64982,0) ~ bgp_community then accept;
            reject;
        };
    };
}

protocol static {
    ipv4;
    # upstream
    route 192.168.0.115/32 via "eth0";

    # upstream dns
    route 172.16.102.35/32 via "tapvpn";
    route 172.16.103.131/32 via "tapvpn";
    route 172.16.103.2/32 via "tapvpn";
    route 78.108.80.1/32 via "tapvpn";
    route 78.108.88.1/32 via "tapvpn";

    # downstreams
    route 192.168.0.110/32 via "eth0";

    route 78.108.87.250/32 via 192.168.0.1;
}

include "/etc/bird/peers/*.conf";

