apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: libvirt
resources:
- ../../base/libvirt
patchesStrategicMerge:
- daemonset.yaml
images:
- name: harbor.home.wugi.info/library/libvirt
  newTag: 20b45da8-1749557427

