protocol bgp guixworkstation {
    local as OWNAS;
    ipv4 {
        next hop self;
        import filter {
            # ci.guix.gnu.org
            if (net = 141.80.181.40/32) then accept;
            # sourceware.org
            if (net = 38.145.34.32/32) then accept;
            reject;
        };
        export none;
    };
    neighbor 192.168.0.191 as 64994;
    multihop;
}
