protocol bgp guixworkstation {
    local as OWNAS;
    ipv4 {
        next hop self;
        import filter {
            # ci.guix.gnu.org
            if (net = 141.80.181.40/32) then accept;
            # substitutes.nonguix.org
            if (net = 144.76.7.123/32) then accept;
            # sourceware.org
            if (net = 38.145.34.32/32) then accept;
            # git2.net-core.org
            if (net = 178.32.80.94/32) then accept;
            # artifacts.elastic.co
            if (net = 34.120.127.130/32) then accept;
            # Hetzner
            if (net = 78.46.0.0/15) then accept;
            # Hamachi
            if (net = 158.120.16.0/20) then accept;
            if (net = 23.210.252.0/22) then accept;
            reject;
        };
        export none;
    };
    neighbor 192.168.0.191 as 64994;
    multihop;
}
