protocol bgp nixoszapret {
    local as OWNAS;
    ipv4 {
       next hop self;
       export none;
       import filter {
           # cloudflare
           if (64993,13335) ~ bgp_community
           then
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           accept;
       };
    };
    neighbor 192.168.0.175 as 64997;
    multihop;
}
