protocol bgp nixostor {
    local as OWNAS;
    ipv4 {
       next hop self;
       import filter {
           # Amazon
           # Amazon CloudFront
           if ((65444,750) ~ bgp_community || (65444,730) ~ bgp_community) then {
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           }
           # Адреса сетей российского сегмента
           if ((65444,900) ~ bgp_community && (65445,643) ~ bgp_community) then {
           then
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           }
           accept;
       };
       export none;
    };
    neighbor 192.168.0.190 as 64995;
    multihop;
}
