protocol bgp nixoszapret {
    local as OWNAS;
    ipv4 {
       next hop self;
       export none;
       import filter {
           # cloudflare
           if (64993,13335,1) ~ bgp_large_community then {
               accept;
           }
           # https://www.pathofexile.com/
           if (64993,13335,2) ~ bgp_large_community then {
               accept;
           }
           # https://gitlab.com/
           if (64993,13335,3) ~ bgp_large_community then {
               accept;
           }
           if (64993,13335) ~ bgp_community then {
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           }
           # akamai linode
           if (64993,63949) ~ bgp_community then {
               bgp_path.prepend(OWNAS);
               bgp_path.prepend(OWNAS);
           }
           accept;
       };
    };
    neighbor 192.168.0.175 as 64997;
    multihop;
}
