protocol bgp nixoshev {
    local as OWNAS;
    ipv4 {
        next hop self;
        import none;
        export filter {
            if (net = 0.0.0.0/0) then {
                bgp_community.add((OWNAS,0));
                accept;
            }
            if (64981,100) ~ bgp_community then accept;
            if (64981,101) ~ bgp_community then accept;
            reject;
        };
    };
    neighbor 192.168.0.115 as 64982;
    multihop;
}

