protocol bgp pc0 {
    local as OWNAS;
    ipv4 {
        next hop self;
        import filter {
            if (net ~ [10.0.0.0/24, 10.0.1.0/24, 10.0.3.0/24])
            then
                accept;
            reject;
        };
        export filter {
            if (net = 0.0.0.0/0) then {
                bgp_community.add((OWNAS,0));
                accept;
            }
            reject;
        };
    };
    neighbor 192.168.0.192 as 64991;
    multihop;
}