log syslog all;

define OWNAS = 64992;
define ANTIFILTER_AS = 64993

protocol device {
}

protocol kernel {
    ipv4 {
        import none;
        export filter {
            if (OWNAS,0) ~ bgp_community then accept;
            if (OWNAS,1) ~ bgp_community then accept;
            if (ANTIFILTER_AS,0) ~ bgp_community then accept;
            reject;
       };
    };
}

ipv4 table upstream_routes;
ipv4 table downstream_routes;

protocol static upstream {
    ipv4 { table upstream_routes; };
    route 192.168.0.180/32 via "eth0";
}

protocol pipe {
    table upstream_routes;
    peer table master4;
    export filter {
        if (net = 192.168.0.180/32)
        then
            bgp_community.add((OWNAS,0));
        accept;
    };
    import none;
};

protocol static downstream {
    ipv4 { table downstream_routes; };
    route 192.168.0.110/32 via "eth0";
}

protocol pipe {
    table downstream_routes;
    peer table master4;
    export filter {
        if (net = 192.168.0.110/32)
        then
            bgp_community.add((OWNAS,1));
        accept;
    };
    import none;
};

include "/etc/bird/peers/*.conf";
