apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: cf88a58a688dc8f1bedb524fd70bb152f92904a5
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-guixsd"
