apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: c303ba582908af7c393600ff941ba567bc2fc615
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-guixsd"
