apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 0fcba4aeb0b5acb7ee4cc07fab727930b3a0afc7
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-guixsd"
        - name: RUNC_ENVIRONMENT
          value: guix
