apiVersion: batch/v1
kind: Job
metadata:
  name: guix-image-workstation
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 102b20fc7c8e92a77a2336a0375fb87735f3afca
