apiVersion: batch/v1
kind: Job
metadata:
  name: guix-image-workstation
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 2a7b01ad41b30266c5018ef5daa4a89c00222a70
