apiVersion: batch/v1
kind: Job
metadata:
  name: guix-image-workstation
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 2c5bd3b34221f569ca34f930d95523ad090a1f37
