apiVersion: batch/v1
kind: Job
metadata:
  name: guix-checkout
  annotations:
    # Setting spec.force to true will make Flux recreate the Job when any
    # immutable field is changed, forcing the Job to run every time the
    # container image tag changes.
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  backoffLimit: 0
  template:
    spec:
      hostNetwork: true
      hostPID: true
      restartPolicy: Never
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          nsenter --target "1" --mount --uts --ipc --net --pid --no-fork \
          /run/setuid-programs/sudo --user oleg --login /bin/sh -le <<EOF
          kubectl "--namespace=${POD_NAMESPACE}" exec --container=guix --stdin=true "pod/${POD_NAME}" -- /bin/sh -le <<'EOL'
          set -o nounset -o errexit -o pipefail -o xtrace
          sudo --user oleg --login /bin/sh -le <<'EOD'
          set -o nounset -o errexit -o pipefail -o xtrace
          env
          cd "${HOME}/src/git.savannah.gnu.org/git/guix" || exit 1
          guix shell git help2man guile-sqlite3 guile-gcrypt gnupg --development guix <<'EOS'
          set -o nounset -o errexit -o pipefail -o xtrace
          git fetch codeberg
          git worktree add -b codeberg/master ../guix-latest
          cd "${HOME}/src/git.savannah.gnu.org/git/guix-latest" || exit 1
          ./bootstrap
          ./configure --localstatedir=/var --prefix=
          make -j$(nproc)
          EOS
          EOD
          EOL
          EOF
        image: docker-registry.wugi.info/library/util-linux-with-udev
        name: nsenter
        resources:
          limits:
            cpu: 14000m
            memory: 4096Mi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          privileged: true
