apiVersion: batch/v1
kind: Job
metadata:
  name: guix-checkout
  annotations:
    # Setting spec.force to true will make Flux recreate the Job when any
    # immutable field is changed, forcing the Job to run every time the
    # container image tag changes.
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  backoffLimit: 0
  template:
    spec:
      hostNetwork: true
      hostPID: true
      restartPolicy: Never
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          nsenter --target "1" --mount --uts --ipc --net --pid --no-fork \
          /run/setuid-programs/sudo --user oleg --login /bin/sh -le <<EOF
          kubectl "--namespace=${POD_NAMESPACE}" exec --container=guix --stdin=true "pod/${POD_NAME}" -- /bin/sh -le <<'EOL'
          id
          EOL
          EOF
        image: docker-registry.wugi.info/library/util-linux-with-udev
        name: nsenter
        resources:
          limits:
            cpu: 14000m
            memory: 4096Mi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          privileged: true
