apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-build
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 74ad586b2db0c7c6f7b8f8ae22093c11c9ea4781
        - name: RUNC_MAKE_TARGET
          value: "pc0"
