apiVersion: v1
kind: Pod
metadata:
  name: runc
spec:
  nodeSelector:
    kubernetes.io/hostname: kube1
  containers:
  - name: runc
    env:
    - name: RUNC_BUNDLE
      value: /srv/runc/nix-builder
    - name: RUNC_CONTAINER_ID
      value: nix-builder
    volumeMounts:
    - mountPath: /srv/runc/nix-builder
      name: runc-nix-builder
  volumes:
  - name: runc-nix-builder
    hostPath:
      path: /srv/runc/nix-builder
      type: Directory
