#!/run/current-system/profile/bin/guile \
--no-auto-compile -e (guile-nsenter) -s
!#

;;;; guile-nsenter --- Run nsenter
;;;; Copyright © 2025 Oleg Pykhalov <go.wigust@gmail.com>
;;;; Released under the GNU GPLv3 or any later version.

(define-module (guile-nsenter)
  #:use-module (srfi srfi-37)
  #:export (main))

;;; Commentary:
;;;
;;; DESCRIPTION
;;;
;;; Code:

(define %options
  (let ((display-and-exit-proc (lambda (msg)
                                 (lambda (opt name arg loads)
                                   (display msg) (quit)))))
    (list (option '(#\v "version") #f #f
                  (display-and-exit-proc "guile-nsenter version 0.0.1\n"))
          (option '(#\h "help") #f #f
                  (display-and-exit-proc
                   "Usage: guile-nsenter ...")))))

(define %default-options
  '())

(define (nsenter-program)
  `(begin
     (define (invoke program . args)
       "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
       (let ((status (apply system* program args)))
         (unless (zero? status)
           (error (format #f "program ~s exited with non-zero code" program)
                  status))
         #t))
     (setenv "PATH" (string-append "/run/current-system/profile/bin:"
                                   "/run/current-system/profile/sbin"))
     (invoke "herd" "start" "runc-container-guix-workstation")
     (invoke "herd" "start" "runc-container-nixos-workstation")
     (invoke "herd" "start" "runc-container-nixos-majordomo")
     (invoke "herd" "start" "windows")))

(define (main args)
  (define opts
    (args-fold (cdr (program-arguments))
               %options
               (lambda (opt name arg loads)
                 (error "Unrecognized option `~A'" name))
               (lambda (op loads)
                 (cons op loads))
               %default-options))
  (define (invoke program . args)
    "Invoke PROGRAM with the given ARGS.  Raise an error if the exit
code is non-zero; otherwise return #t."
    (let ((status (apply system* program args)))
      (unless (zero? status)
        (error (format #f "program ~s exited with non-zero code" program)
               status))
      #t))
  (apply invoke
         `("nsenter"
           ,(string-append "--target=" (number->string 1))
           "--mount"
           "--uts"
           "--ipc"
           "--net"
           "--pid"
           "--no-fork"
           ,@(or (and=> (getenv "NSENTER_UID")
                        (lambda (uid)
                          (list (string-append "--setuid=" uid))))
                 '())
           ,@(or (and=> (getenv "NSENTER_GID")
                        (lambda (gid)
                          (list (string-append "--setgid=" gid))))
                 '())
           "/run/current-system/profile/bin/guile" "--no-auto-compile"
           "-c" ,(with-output-to-string (lambda () (write (nsenter-program))))))
  (while #t
    (sleep 10)))

;;; guile-nsenter ends here
