log "/var/log/bird.log" all;

define OWNAS = 64995;
define OWNIP = 192.168.0.190;
define OWNNET = 192.168.0.0/24;
define OWNNETSET = [192.168.0.0/24+];

router id OWNIP;

protocol device {
    scan time 10;
}

protocol kernel {
    learn;
    ipv4 {
        import none;
        export filter { if (net = 0.0.0.0/0) then accept; reject; };
    };
}

protocol static {
    route OWNNET reject;

    ipv4 {
        import all;
        export all;
    };
}

protocol static {
    ipv4;

    # habr.com
    route 178.248.237.68/32 via "eth0";

    # cdn.7tv.app
    route 37.27.0.0/16 via "eth0";

    # substitutes.nonguix.org
    route 144.76.7.123/32 via "eth0";

    # discord.com
    route 104.19.229.21/32 via "eth0";
    route 104.19.230.21/32 via "eth0";
    route 162.159.128.233/32 via "eth0";
    route 162.159.130.234/32 via "eth0";
    route 162.159.133.233/32 via "eth0";
    route 162.159.134.233/32 via "eth0";
    route 162.159.135.232/32 via "eth0";
    route 162.159.135.234/32 via "eth0";
    route 162.159.136.232/32 via "eth0";
    route 162.159.136.234/32 via "eth0";
    route 162.159.137.232/32 via "eth0";
    route 162.159.138.232/32 via "eth0";
    route 216.150.1.129/32 via "eth0";
    route 216.150.16.193/32 via "eth0";
    route 64.233.164.100/32 via "eth0";
    route 64.233.164.113/32 via "eth0";
    route 64.233.165.106/32 via "eth0";
    route 64.233.165.198/32 via "eth0";

}

include "/etc/bird/peers/*.conf";

