log syslog all;

define OWNAS = 64995;

protocol device {
}

protocol kernel {
    ipv4 {
        import none;
        export filter {
            if (source = RTS_STATIC) && (net = 192.168.0.180/32) then accept;
            if (64993,0) ~ bgp_community then accept;
            reject;
        };
    };
}

protocol static {
    ipv4;
    route 192.168.0.180/32 via "eth0";

    # habr.com
    route 178.248.237.68/32 via "eth0";

    # cdn.7tv.app
    route 37.27.0.0/16 via "eth0";

    # substitutes.nonguix.org
    route 144.76.7.123/32 via "eth0";
}

include "/etc/bird/peers/*.conf";

