log "/var/log/bird.log" all;

define OWNAS = 64995;

protocol device {
}

protocol direct {
}

protocol kernel {
    ipv4 {
        import none;
        export all;
    };
}

protocol static {
    ipv4;
    route 192.168.0.180/32 via "eth0";

    # habr.com
    route 178.248.237.68/32 via "eth0";

    # cdn.7tv.app
    route 37.27.0.0/16 via "eth0";

    # substitutes.nonguix.org
    route 144.76.7.123/32 via "eth0";
}

ipv4 table downstream_routes;

protocol pipe {
    table master4;
    peer table downstream_routes;
    export all;
    import none;
};

include "/etc/bird/peers/*.conf";

