apiVersion: v1
kind: Pod
metadata:
  name: runc
  labels:
    app.kubernetes.io/name: runc-kube3-guix-workstation
    app.kubernetes.io/part-of: guix
spec:
  nodeSelector:
    kubernetes.io/hostname: kube3
  tolerations:
  - key: workstation.cluster.local
    operator: Equal
    value: 'true'
    effect: NoSchedule
  containers:
  - name: runc
    env:
    - name: RUNC_BUNDLE
      value: /srv/runc/guix-workstation
    - name: RUNC_CONTAINER_ID
      value: guix-workstation
    ports:
    - containerPort: 5556
      name: guix
      protocol: TCP
    - containerPort: 22
      name: ssh
      protocol: TCP
    volumeMounts:
    - mountPath: /srv/runc/guix-workstation
      name: runc-guix-workstation
  volumes:
  - name: runc-guix-workstation
    hostPath:
      path: /srv/runc/guix-workstation
      type: Directory
