apiVersion: v1
kind: Service
metadata:
  name: runc-kube1
  labels:
    app.kubernetes.io/name: runc-kube1-guix-workstation
    app.kubernetes.io/part-of: guix
spec:
  ports:
  - port: 5556
    protocol: TCP
    targetPort: 5556
    name: guix
  - port: 22
    protocol: TCP
    targetPort: 22
    name: ssh
  selector:
    app.kubernetes.io/name: runc-kube1-guix-workstation
    app.kubernetes.io/part-of: guix
  type: ClusterIP
