apiVersion: v1
kind: Endpoints
metadata:
  name: workstation-kube3
  labels:
    app.kubernetes.io/name: workstation-kube3
    app.kubernetes.io/part-of: workstation
subsets:
- addresses:
  - ip: 192.168.0.194
  ports:
  - port: 80
    name: http
