namespace: workstation
## Append samples of your project ##
resources:
- workstation_v1_workstation.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
images:
- name: harbor.home.wugi.info/library/guix-image-workstation
  newTag: HEAD-a8a2c200-1753762154
- name: harbor.home.wugi.info/library/nixos-systemd-taskexecutor
  newTag: HEAD-e33332a2-1752685160
- name: harbor.home.wugi.info/library/archlinux-systemd
  newTag: 4309f8ae
