namespace: workstation
## Append samples of your project ##
resources:
- workstation_v1_workstation.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
images:
- name: harbor.home.wugi.info/library/guix-image-workstation
  newTag: HEAD-755a8650-1747596405
- name: harbor.home.wugi.info/library/nixos-systemd-taskexecutor
  newTag: fc622b88
- name: harbor.home.wugi.info/library/archlinux-systemd
  newTag: 4309f8ae
