apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
  annotations:
    # Setting spec.force to true will make Flux recreate the Job when any
    # immutable field is changed, forcing the Job to run every time the
    # container image tag changes.
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  backoffLimit: 0
  template:
    spec:
      hostNetwork: true
      hostPID: true
      restartPolicy: Never
      containers:
      - command:
        - /bin/guile
        - --no-auto-compile
        - -e
        - (guile-nsenter)
        - -s
        - /usr/local/bin/guile-script.scm
        image: harbor.home.wugi.info/library/util-linux-with-udev:44cd2b5c
        name: nsenter
        resources:
          limits:
            cpu: 14000m
            memory: 8192Mi
          requests:
            cpu: 50m
            memory: 8192Mi
        volumeMounts:
        - mountPath: /usr/local/bin/guile-nsenter
          name: script
          subPath: guile-nsenter
          readOnly: true
        - mountPath: /usr/local/bin/certgen.sh
          name: certgen
          subPath: certgen.sh
          readOnly: true
        - mountPath: /mnt/etc/kubernetes/pki/ca.crt
          name: kubernetes-pki-ca-cert
          readOnly: true
        - mountPath: /mnt/etc/kubernetes/pki/ca.key
          name: kubernetes-pki-ca-key
          readOnly: true
        - mountPath: /etc/kubeedge
          name: kubeedge-certs
      volumes:
      - name: script
        configMap:
          name: script
      - name: certgen
        configMap:
          name: kubeedge-certgen
      - name: kubernetes-pki-ca-cert
        hostPath:
          path: /etc/kubernetes/pki/ca.pem
          type: File
      - name: kubernetes-pki-ca-key
        hostPath:
          path: /etc/kubernetes/pki/ca.key
          type: File
      - name: kubeedge-certs
        hostPath:
          path: /etc/kubeedge-certs
          type: Directory
