apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonlight-web-stream
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: moonlight-web-stream.cluster.local/schedulable
                operator: In
                values:
                - "true"
      tolerations:
      - key: "workstation.cluster.local"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: moonlight-web-stream
