apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 9c913ab7fbada80ff3dc79943d9408c6706634e0
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-libvirt"
        - name: RUNC_ENVIRONMENT
          value: guix
