apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 730dc6479cad3e9da7caf16f99e3f6466d876ea9
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-libvirt"
        - name: RUNC_ENVIRONMENT
          value: guix
