apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: f69d87c35701d808a61c1ae64a154af8abf225c9
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-libvirt"
        - name: RUNC_ENVIRONMENT
          value: guix
