(use-modules (gnu)
             (ng0 packages chromium))

(define packages
  '("alsa-utils"
    "pulseaudio" "ponymix" "pavucontrol"
    "aspell" "aspell-dict-en" "aspell-dict-ru" "shellcheck"
    "translate-shell"
    "gettext"
    "bzip2" "unzip"
    "magit" "emacs-git-gutter" "emacs-git-timemachine" "git-modes"
    "emacs-erc-hl-nicks"
    "git"
    "mercurial"
    "guile" "guile-git" "guile-ssh" "guix"
    "ghostscript-with-x"
    "gs-fonts" "emacs-auctex" "texlive" "texinfo" "graphviz"
    "lua" "emacs-lua-mode"
    "node" "php" "emacs-web-mode" "emacs-request"
    "conkeror" "icecat" "chromium"
    "python-internetarchive"
    "haunt" "python-ghp-import"
    "icedtea" "emacs-cider"
    "emacs-rpm-spec-mode" "emacs-nix-mode"
    "emacs-sx"
    "emacs-slime"
    "racket"
    "haskell-mode" "ghc" "xmobar" "xmonad" "ghc-xmonad-contrib"
    "ocaml"
    "emacs-org" "emacs-org-edit-latex" "emacs-org-pomodoro"
    "emacs-ag"
    "the-silver-searcher" "cloc"
    "emacs-company"
    "emacs-undo-tree" "emacs-flx" "emacs-projectile"
    "emacs-smex"
    "emacs-multiple-cursors" "emacs-smartparens"
    "emacs-aggressive-indent"
    "emacs-transpose-frame"
    "emacs-engine-mode"
    "emacs-expand-region"
    "emacs-dired-hacks" "emacs-pdf-tools"
    "emacs-which-key"
    "emacs-yasnippet" "emacs-yasnippet-snippets"
    "emacs-writegood-mode"
    "emacs-rainbow-delimiters" "emacs-rainbow-identifiers" "emacs-rainbow-mode"
    "emacs-async" "emacs-use-package"
    "feh" "gimp"
    "ffmpeg" "mpv" "mps-youtube" "youtube-dl"
    "file" "htop" "ncdu" "neofetch" "tree" "stow" "strace"
    "parallel" "adb"
    "adwaita-icon-theme"
    "fontconfig" "font-adobe-source-han-sans" "font-hack"
    "font-wqy-zenhei"
    "gcc-toolchain" "gdb" "gnu-c-manual" "json-c"
    "autoconf" "automake" "make" "m4" "pkg-config"
    "clang" "help2man"
    "gnupg" "libgcrypt" "pinentry" "paperkey" "password-store"
    "libreoffice"
    "isync" "mailutils" "notmuch" "emacs-debbugs" "emacs-gitpatch"
    "maxima" "proof-general" "gnuplot"
    "mysql" "sqlite"
    "openssh" "nmap" "ethtool" "wakelan" "iperf"
    "perl"
    "qemu" "virt-viewer"
    "rsync" "rsnapshot"
    "samba"
    "rxvt-unicode"
    "screen" "tmux"
    "vera" "sicp" "man-pages"
    "tome4"
    "aria2" "wget"
    "xclip" "wgetpaste"
    "xdotool" "xev" "xinit" "xlsfonts" "xorg-server" "xprop"
    "xrdb" "xset" "xmodmap" "setxkbmap"
    "desktop-file-utils" "redshift"))

(packages->manifest (map (compose list
                                  specification->package+output) packages))
