{
 "title": "OBS",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(obs_encoder_info{job=\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(obs_encoder_info,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Output Activity",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "obs_output_active{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "output: {{output_id}}: {{output_name}}"
    }
   ]
  },
  {
   "title": "Microphone Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "obs_source_channel_magnitude{instance=\"$node\", job=\"$job\", source_id=\"pipewire_audio_input_capture\"}",
     "legendFormat": "Average: {{source_name}}: channel {{channel_id}}"
    },
    {
     "expr": "obs_source_channel_peak{instance=\"$node\", job=\"$job\", source_id=\"pipewire_audio_input_capture\"}",
     "legendFormat": "Peak: {{source_name}}: channel {{channel_id}}"
    }
   ]
  },
  {
   "title": "Average Frame Rendering Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "obs_global_average_frame_time_ns{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Output Frames Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(obs_output_frames{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "{{output_id}}: {{output_name}}"
    }
   ]
  },
  {
   "title": "Problematic Frames Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(obs_global_lagged_frames_total{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "lagged"
    },
    {
     "expr": "irate(obs_global_video_skipped_frames_total{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "skipped"
    },
    {
     "expr": "irate(obs_output_dropped_frames_total{instance=\"$node\", job=\"$job\"}[5m])",
     "legendFormat": "dropped: {{output_id}}: {{output_name}}"
    }
   ]
  },
  {
   "title": "Output Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(obs_output_bytes_total{instance=\"$node\", job=\"$job\"}[5m]) * 8",
     "legendFormat": "{{output_id}}: {{output_name}}"
    },
    {}
   ]
  }
 ]
}