apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nmap-prometheus-exporter
resources:
- namespace.yaml
- deployment.yaml
configMapGenerator:
- name: nmap-prometheus-exporter-configuration
  files:
  - portscanip.nmap=rootfs/app/portscanip.nmap
