log syslog all;

define OWNAS = 64998;

protocol device {
}

protocol kernel {
    ipv4 {
        import none;
        export filter {
            if (source = RTS_STATIC) && (net = 192.168.0.115/32) then accept;
            if (64982,0) ~ bgp_community then accept;
            reject;
        };
    };
}

protocol static {
    ipv4;
    route 192.168.0.115/32 via "eth0";
}

include "/etc/bird/peers/*";
