log syslog all;

define OWNAS = 64998;

protocol device {
}

protocol kernel {
    ipv4 {
        import none;
        export filter {
            if (source = RTS_STATIC) then accept;
            if (64982,0) ~ bgp_community then accept;
            reject;
        };
    };
}

protocol kernel {
    ipv6 {
        import none;
        export filter {
            if (source = RTS_STATIC) then accept;
            reject;
        };
    };
}

protocol static {
    ipv4;
    route 192.168.0.0/24 via "eth0";

    # amazon twitch
    route 35.160.0.0/12 via 192.168.0.180;
    route 44.192.0.0/10 via 192.168.0.180;
    route 52.0.0.0/11 via 192.168.0.180;
    route 52.32.0.0/13 via 192.168.0.180;
    route 52.40.0.0/14 via 192.168.0.180;
    route 54.160.0.0/11 via 192.168.0.180;
    route 54.64.0.0/11 via 192.168.0.180;
}

protocol static {
    ipv6;
    route fc00::/7 blackhole;
}

include "/etc/bird/peers/*";
