apiVersion: batch/v1
kind: Job
metadata:
  name: fetch-images
  annotations:
    # Setting spec.force to true will make Flux recreate the Job when any
    # immutable field is changed, forcing the Job to run every time the
    # container image tag changes.
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  template:
    spec:
      containers:
      - name: fetch
        env:
        - name: FETCH_IMAGES_KUSTOMIZATION_FILE
          value: /home/oleg/.local/share/chezmoi/apps/cluster1/workstation/workstation-kube3/kustomization.yaml
        - name: GIT_COMMIT
          value: 755a865020ab4c2e305dd578dab0da227d8df0f9
      nodeSelector:
        kubernetes.io/hostname: kube3
      tolerations:
        - key: workstation.cluster.local
          operator: Equal
          value: 'true'
          effect: NoSchedule
