# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

light_theme: false
clients:
- type: openai-compatible
  name: ollama
  api_base: http://192.168.0.185:11434/v1
  models:
  - name: gemma3:12b
