#!/usr/bin/env bash

if [[ "$GIT_JENKINS" == true ]]
then
    branch="$(git rev-parse --abbrev-ref HEAD)"

    case $branch in
        wip-local)
            exec -a "$0" $HOME/bin/jenkins build guix maintenance
            ;;
        master)
            exec -a "$0" $HOME/bin/jenkins build guix upstream
            ;;
    esac
fi
