apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-reconfigure
spec:
  template:
    metadata:
      annotations:
        guix-default-channel-commit: 814ea5bd
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube3
      containers:
      - name: refresh
        env:
        - name: GIT_COMMIT
          value: 552c0944c039c031db0fbf1bb223ed2a196b4182
        - name: GUIX_SYSTEM
          value: pc0
      tolerations:
      - key: workstation.cluster.local
        operator: Equal
        value: 'true'
        effect: NoSchedule
