apiVersion: batch/v1
kind: Job
metadata:
  name: guix-system-reconfigure
spec:
  template:
    metadata:
      annotations:
        guix-default-channel-commit: 814ea5bd
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube3
      containers:
      - name: refresh
        env:
        - name: GIT_COMMIT
          value: 51cd3bdc1745b86719bebd28fda1d0ba7215d46f
        - name: GUIX_SYSTEM
          value: pc0
        - name: HOME
          value: /home/oleg
      tolerations:
      - key: workstation.cluster.local
        operator: Equal
        value: 'true'
        effect: NoSchedule
