log "/var/log/bird.log" all;

################################################
#               Variable header                #
################################################

define OWNAS = 64997;
define OWNIP = 192.168.0.175;
define OWNNET = 192.168.0.0/24;
define OWNNETSET = [192.168.0.0/24+];

################################################
#                 Header end                   #
################################################

router id OWNIP;

protocol device {
    scan time 10;
}

template bgp localpeers {
    local as OWNAS;
    path metric 1;

    ipv4 {
        next hop self;
        import all;
        export all;
    };
}

template bgp dnpeers {
    local as OWNAS;
    path metric 1;

    ipv4 {
        next hop self;
        import all;
        export none;
    };
}

include "/etc/bird/peers/*";
