#!/run/current-system/profile/bin/guile \
--no-auto-compile -e (guile-nsenter) -s
!#

;;;; guile-nsenter --- Run nsenter
;;;; Copyright © 2025 Oleg Pykhalov <go.wigust@gmail.com>
;;;; Released under the GNU GPLv3 or any later version.

(define-module (guile-nsenter)
  #:use-module (srfi srfi-37)
  #:export (main))

;;; Commentary:
;;;
;;; DESCRIPTION
;;;
;;; Code:

(define %options
  (let ((display-and-exit-proc (lambda (msg)
                                 (lambda (opt name arg loads)
                                   (display msg) (quit)))))
    (list (option '(#\v "version") #f #f
                  (display-and-exit-proc "guile-nsenter version 0.0.1\n"))
          (option '(#\h "help") #f #f
                  (display-and-exit-proc
                   "Usage: guile-nsenter ...")))))

(define %default-options
  '())

(define (guile-with-environment expression)
  `(let* ((user (getpw (getuid)))
          (name (passwd:name user))
          (shell (passwd:shell user)))
     (execl shell shell "--login" "-c"
            (with-output-to-string
              (lambda ()
                (write
                 (list
                  "/run/current-system/profile/bin/guile" "--no-auto-compile"
                  "-c" ,(with-output-to-string
                          (lambda ()
                            (write expression))))))))))

(define (runc-code)
  '(begin
     (define (git . args)
       (apply system* (append '("guix" "shell" "git" "--" "git") args)))
     (and=> (getenv "HOME")
            (lambda (home)
              (let ((commit (getenv "GIT_COMMIT"))
                    (workdir
                     (mkdtemp
                      (string-append
                       home "/.cache/wigust/checkouts/dotfiles.XXXXXXXXXX"))))
                (chdir workdir)
                (and
                 (zero? (git "init"))
                 (zero? (git "remote" "add" "origin" "https://cgit.wugi.info/git/wigust/dotfiles"))
                 (zero? (git "fetch" "--depth" (number->string 1) "origin" commit))
                 (zero? (git "checkout" commit))
                 ;; TODO: Do not copy openssh.scm from other location.
                 (copy-file (string-append home "/openssh.scm")
                            "wugi/home/config/openssh.scm")
                 ;; TODO: Do not copy intr.json from other location.
                 (copy-file (string-append home "/intr.json")
                            "wugi/etc/mjru/intr.json")
                 (zero? (system* "guix" "shell" "git" "make" "skopeo" "--"
                                 "make" "guix-image-workstation"))))))))

(define (kubectl-program)
  ;; TODO: Do not hardcode Kubernetes namespace.
  ;; TODO: Do not hardcode uid and gid.
  ;; TODO: Do not hardcode runc container name.
  ;; TODO: Use Kubernetes HTTP API without kubectl.
  `(begin
     (setenv "KUBECONFIG" "/home/oleg/.kube/config")
     (system* "/home/oleg/.guix-profile/bin/kubectl" "--namespace=guix"
              "exec" "--stdin=true"
              ,(string-append "pod/" (getenv "RUNC_CONTAINER_ID")) "--"
              "runc" "exec"
              "--user" "1000:998"
              "--env" (string-append "GIT_COMMIT=" (getenv "GIT_COMMIT"))
              "guix-builder"
              "/run/current-system/profile/bin/guile" "--no-auto-compile"
              "-c" ,(with-output-to-string
                      (lambda ()
                        (write
                         (guile-with-environment (runc-code))))))))

(define (main args)
  (define opts
    (args-fold (cdr (program-arguments))
               %options
               (lambda (opt name arg loads)
                 (error "Unrecognized option `~A'" name))
               (lambda (op loads)
                 (cons op loads))
               %default-options))
  (system* "nsenter"
           (string-append "--target=" (number->string 1))
           "--mount"
           "--uts"
           "--ipc"
           "--net"
           "--pid"
           "--no-fork"
           ;; TODO: Do not hardcode uid and gid.
           (string-append "--setuid=" (number->string 1000))
           (string-append "--setgid=" (number->string 998))
           "/usr/bin/env"
           (string-append "GIT_COMMIT=" (getenv "GIT_COMMIT"))
           (string-append "RUNC_CONTAINER_ID=" (getenv "RUNC_CONTAINER_ID"))
           "/run/current-system/profile/bin/guile" "--no-auto-compile"
           "-c" (with-output-to-string (lambda () (write (kubectl-program))))))

;;; guile-nsenter ends here
