#!/run/current-system/profile/bin/guile \
--no-auto-compile -e (guile-nsenter) -s
!#

;;;; guile-nsenter --- SYNOPSIS
;;;; Copyright © 2025 Oleg Pykhalov <go.wigust@gmail.com>
;;;; Released under the GNU GPLv3 or any later version.

(define-module (guile-nsenter)
  #:use-module (srfi srfi-37)
  #:export (main))

;;; Commentary:
;;;
;;; DESCRIPTION
;;;
;;; Code:

;; (define (bash-code)
;;   "\
;; set -o nounset -o errexit -o pipefail -o xtrace
;; mkdir -p \"${HOME}/.cache/wigust\"
;; TMPDIR=\"${HOME}/.cache/wigust/checkouts\" mktemp -d -t \"dotfiles.XXXXXXXXXX\"
;; cd \"$TMPDIR\" || exit 1
;; guix shell git -- git clone --depth 1 https://cgit.wugi.info/git/wigust/dotfiles \"$TMPDIR\"
;; guix shell git gnupg skopeo --development guix -- make guix-image-workstation")

(define %options
  (let ((display-and-exit-proc (lambda (msg)
                                 (lambda (opt name arg loads)
                                   (display msg) (quit)))))
    (list (option '(#\v "version") #f #f
                  (display-and-exit-proc "executable_guile-nsenter version 0.0.1\n"))
          (option '(#\h "help") #f #f
                  (display-and-exit-proc
                   "Usage: executable_guile-nsenter ...")))))

(define %default-options
  '())

(define (runc-code)
  '(begin
     (and=> (getenv "HOME")
            (lambda (home)
              (let ((guix "/run/current-system/profile/bin/guix")
                    (commit (getenv "GIT_COMMIT"))
                    (workdir (mkdtemp (string-append home "/.cache/wigust/checkouts/dotfiles.XXXXXXXXXX"))))
                (chdir workdir)
                (system* guix "shell" "git" "--" "git" "init")
                (system* guix "shell" "git" "--" "git" "remote" "add" "origin" "https://cgit.wugi.info/git/wigust/dotfiles")
                (system* guix "shell" "git" "--" "git" "fetch" "--depth" (number->string 1) "origin" commit)
                (system* guix "shell" "git" "--" "git" "checkout" commit)
                (system* guix "shell" "git" "make" "skopeo" "--" "guix-image-workstation"))))))

(define (kubectl-program)
  ;; TODO: Do not hardcode Kubernetes namespace.
  ;; TODO: Do not hardcode uid and gid.
  ;; TODO: Do not hardcode runc container name.
  ;; TODO: Use Kubernetes HTTP API without kubectl.
  `(begin
     (setenv "KUBECONFIG" "/home/oleg/.kube/config")
     (system* "/home/oleg/.guix-profile/bin/kubectl" "--namespace=guix"
              "exec" "--stdin=true" "pod/runc-kube1-guix-builder" "--"
              "runc" "exec"
              "--user" "1000:998"
              "--env" (string-append "GIT_COMMIT=" (getenv "GIT_COMMIT"))
              "guix-builder"
              "/run/current-system/profile/bin/guile"
              "-c" ,(with-output-to-string (lambda () (write (runc-code)))))))

(define (main args)
  (define opts
    (args-fold (cdr (program-arguments))
               %options
               (lambda (opt name arg loads)
                 (error "Unrecognized option `~A'" name))
               (lambda (op loads)
                 (cons op loads))
               %default-options))
  (system* "nsenter"
           (string-append "--target=" (number->string 1))
           "--mount"
           "--uts"
           "--ipc"
           "--net"
           "--pid"
           "--no-fork"
           ;; TODO: Do not hardcode uid and gid.
           (string-append "--setuid=" (number->string 1000))
           (string-append "--setgid=" (number->string 998))
           "/usr/bin/env"
           (string-append "GIT_COMMIT=" (getenv "GIT_COMMIT"))
           "/run/current-system/profile/bin/guile"
           "-c" (with-output-to-string (lambda () (write (kubectl-program))))))

;;; executable_guile-nsenter ends here
