apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 21833b00c88a41248a3cd920086ddddd8ad27abe
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
