apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 66c8065a7f81919cfa8c2ba70906209e7b55794a
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-build-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
