apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 7cc650354ae9888d394c17f59c19706a9e47a7e9
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-home-build-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
