
(defcommand sudo () ()
  (run-shell-command "xterm & sleep 2 ; xdotool type 'ssh web33s' ; xdotool key Return; sleep 2 ; xdotool type 'sudo -i' ; xdotool key Return ; sleep 2; xdotool type '***REMOVED***' ; xdotool key Return"))

(defmacro define-web (n)
  `(progn
     (defcommand ,(intern (concat "web" (write-to-string n))) () ()
       (run-shell-command ,(concat "xterm & sleep 2 ; xdotool type 'ssh web" (write-to-string n) "s' ; xdotool key Return; sleep 2 ; xdotool type 'sudo -i' ; xdotool key Return ; sleep 2; xdotool type '***REMOVED***' ; xdotool key Return")))))

(define-web 15)
(define-web 16)
(define-web 17)
(define-web 18)
(define-web 19)
(define-web 20)
(define-web 21)
(define-web 22)
(define-web 23)
(define-web 24)
(define-web 25)
(define-web 26)
(define-web 27)
(define-web 28)
(define-web 29)
(define-web 30)
(define-web 31)
(define-web 32)
(define-web 33)
(define-web 34)
(define-web 35)
(define-web 36)
(define-web 37)
