(use-modules (erza key-binding-group))

(key-binding-group
 (description "User-defined bindings")
 (prefix "C-c")
 (keys (list (key-binding (key "A") (command #f))
             (key-binding (key "a") (command #f))
             (key-binding (key "B") (command 'ibuffer))
             (key-binding (key "b") (command 'ivy-switch-buffer))
             (key-binding (key "C") (command #f))
             (key-binding (key "c") (command #f))
             (key-binding (key "D") (command #f))
             (key-binding (key "d") (command #f))
             (key-binding (key "E") (command #f))
             (key-binding (key "e") (command #f))
             (key-binding (key "F") (command #f))
             (key-binding (key "f") (command 'ffap))
             (key-binding (key "G") (command #f))
             (key-binding (key "g") (command 'counsel-rg))
             (key-binding (key "H") (command #f))
             (key-binding (key "h") (command #f))
             (key-binding (key "I") (command #f))
             (key-binding (key "i") (command 'wi-dabbrev-expand))
             (key-binding (key "J") (command #f))
             (key-binding (key "j") (command #f))
             (key-binding (key "K") (command #f))
             (key-binding (key "k") (command #f))
             (key-binding (key "L") (command #f))
             (key-binding (key "l") (command 'helm-recentf))
             (key-binding (key "M") (command #f))
             (key-binding (key "m") (command #f))
             (key-binding (key "N") (command #f))
             (key-binding (key "n") (command #f))
             (key-binding (key "O") (command #f))
             (key-binding (key "o") (command 'swiper))
             (key-binding (key "P") (command #f))
             (key-binding (key "p") (command #f))
             (key-binding (key "Q") (command #f))
             (key-binding (key "q") (command #f))
             (key-binding (key "R") (command #f))
             (key-binding (key "r") (command 'revert-buffer))
             (key-binding (key "S") (command #f))
             (key-binding (key "s") (command 'scratch))
             (key-binding (key "T") (command #f))
             (key-binding (key "t") (command #f))
             (key-binding (key "U") (command #f))
             (key-binding (key "u") (command #f))
             (key-binding (key "V") (command #f))
             (key-binding (key "v") (command 'magit))
             (key-binding (key "W") (command #f))
             (key-binding (key "w") (command #f))
             (key-binding (key "X") (command #f))
             (key-binding (key "x") (command 'helm-M-x))
             (key-binding (key "Y") (command #f))
             (key-binding (key "y") (command #f))
             (key-binding (key "Z") (command #f))
             (key-binding (key "z") (command #f)))))
