(("Default" 3 T T :CLASS "Emacs" :INSTANCE "emacs-26_1" :TITLE "#guix" :ROLE NIL)
 ("Default" 5 T T :CLASS "Emacs" :INSTANCE "emacs-26_1" :TITLE "#scheme" :ROLE NIL)
 ("Default" 7 T T :CLASS "Firefox" :TITLE  "Grafana - fiore - Mozilla Firefox")
 ("Default" 3 NIL NIL :TITLE "youtube-dl")
 ("Default" 0 NIL T :CLASS "mpv" :TITLE "emacs-emms")
 ("youtube" 0 T NIL :CLASS "mpv") ("youtube" 2 T NIL :CLASS "Firefox")
 ("youtube" 3 T NIL :CLASS "XTerm"))
