# Warning: 'patchesStrategicMerge' is deprecated. Please use 'patches' instead. Run 'kustomize edit fix' to update your Kustomization automatically.
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: git
spec:
  jobTemplate:
    spec:
      activeDeadlineSeconds: 82800
      backoffLimit: 0
      template:
        spec:
          containers:
          - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --no-fork
            - --setuid=1000
            - --setgid=998
            - /run/current-system/profile/bin/bash
            - -l
            - -c
            - |
              set -o nounset -o errexit -o pipefail -o xtrace
              /usr/bin/env
              cd "$WORKING_DIR" || exit 1
              git for-each-repo --config=maintenance.repo git maintenance run --task=prefetch
            env:
            - name: "HOME"
              value: "/home/oleg"
            - name: "USER"
              value: "oleg"
            - name: "WORKING_DIR"
              value: "/home/oleg"
            image: docker-registry.wugi.info/library/util-linux-with-udev
            name: git
            resources:
              limits:
                cpu: 14000m
                memory: 4096Mi
              requests:
                cpu: 1000m
                memory: 512Mi
            securityContext:
              privileged: true
          hostNetwork: true
          hostPID: true
          nodeSelector:
            kubernetes.io/hostname: kube1
          restartPolicy: Never
  schedule: 30 18 * * *
  suspend: false
