log "/var/log/bird.log" all;

define OWNAS = 64982;
define OWNIP = 192.168.0.115;
define OWNNET = 192.168.0.0/24;
define OWNNETSET = [192.168.0.0/24+];

router id OWNIP;

protocol device {
    scan time 10;
}

protocol kernel {
    learn;
    ipv4 {
        import none;
        export filter { if (net = 0.0.0.0/0) then accept; reject; };
    };
}

include "/etc/bird/peers/*.conf";

