(define-module (wugi home config pc0)
  #:use-module (gnu home)
  #:use-module (gnu home services)
  #:use-module (gnu home services desktop)
  #:use-module (gnu home services mcron)
  #:use-module (gnu home services shells)
  #:use-module (gnu home services ssh)
  #:use-module (gnu home services sound)
  #:use-module (gnu services)
  #:use-module (gnu packages xorg)
  #:use-module (guix gexp)
  #:use-module (wugi home services audio)
  #:use-module (wugi home services desktop)
  #:use-module (wugi home services shell)
  #:use-module (wugi home services mime)
  #:use-module (wugi home services gdb)
  #:use-module (wugi home services version-control)
  #:use-module (wugi home services emacs)
  #:use-module (wugi home services tmux)
  #:use-module (wugi home services linux)
  #:use-module (wugi home services nix)
  #:use-module (wugi home services terminals)
  #:use-module (wugi home services haskell-apps)
  #:use-module (wugi home services gtk)
  #:use-module (wugi home services rust-apps)
  #:use-module (wugi home services lisp)
  #:use-module (wugi home services python)
  #:use-module (wugi home services nano)
  #:use-module (wugi home services dns)
  #:use-module (wugi home services web)
  #:use-module (wugi home services gnupg)
  #:use-module (wugi home services groovy)
  #:use-module (wugi home services guile)
  #:use-module (wugi home services kodi)
  #:use-module (wugi home services mail)
  #:use-module (wugi home services databases)
  #:use-module (wugi home services video)
  #:export (%pc0-home-environment))

(define (%pc0-home-environment)
  (home-environment
    (services (list (service home-bash-service-type)))))
