log "/var/log/bird.log" all;

define OWNAS = 64983;
define OWNIP = 192.168.0.110;
define OWNNET = 192.168.0.0/24;
define OWNNETSET = [192.168.0.0/24+];

router id OWNIP;

protocol device {
    scan time 10;
}

protocol kernel {
    learn;
    ipv4 {
        import none;
        export all;
    };
}

include "/etc/bird/peers/*.conf";

