logoutput: syslog
debug: 9

external: eth0
internal: eth0 port = 1080

timeout.io: 60

clientmethod: none
socksmethod: none
user.unprivileged: nobody

client pass {
    from: 0.0.0.0/0 port 1-65535 to: 0.0.0.0/0
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    protocol: tcp udp
}

route {
    from: 0.0.0.0/0 to: .torproject.org via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: rutracker.org via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: .rutracker.org via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: .rutracker.cc via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: .t-ru.org via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: .openbittorrent.com via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: .opentrackr.org via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: .playground.ru via: 127.0.0.1 port = 9050
    proxyprotocol: socks_v5
}

route {
    from: 0.0.0.0/0 to: 0.0.0.0/0 via: 192.168.0.110 port = 1081
    proxyprotocol: socks_v5
}
