logoutput: syslog
debug: 0

external: eth0
internal: eth0 port = 1080

timeout.io: 600

clientmethod: none
socksmethod: none
user.unprivileged: nobody

resolveprotocol: tcp

client pass {
    from: 0.0.0.0/0 port 1-65535 to: 0.0.0.0/0
}

socks pass {
    from: 0.0.0.0/0 to: 0.0.0.0/0
    protocol: tcp udp
}

route {
    from: 0.0.0.0/0 to: 0.0.0.0/0 via: 192.168.0.110 port = 1081
    proxyprotocol: socks_v5
}
