apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic
spec:
  schedule: "15 22 * * *" # every day
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/hostname: kube1
          containers:
          - name: restic
            env:
            - name: RESTIC_SCRIPT
              value: restic-backup-system
