apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 6db7c63b1c03e7a6c483073da3c976bf8fc79b44
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-image-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
