apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 50b6eba2aa81ac28c0d34a32b79a0c9d5316b2e8
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-image-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
