apiVersion: batch/v1
kind: Job
metadata:
  name: invoke-runc
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
      containers:
      - name: nsenter
        env:
        - name: GIT_COMMIT
          value: 51e35f5b6827972c6df53d770cb5e8ec77023016
        - name: RUNC_MAKE_TARGET
          value: "guix-time-machine-system-image-workstation"
        - name: RUNC_ENVIRONMENT
          value: guix
