apiVersion: batch/v1
kind: CronJob
metadata:
  name: mbsync
  annotations:
    # Setting spec.force to true will make Flux recreate the Job when any
    # immutable field is changed, forcing the Job to run every time the
    # container image tag changes.
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mbsync
            env:
            - name: MBSYNC_IMAP_ACCOUNT
              value: majordomo-healthchecks
          nodeSelector:
            kubernetes.io/hostname: kube1
