apiVersion: batch/v1
kind: Job
metadata:
  name: runc-guix-builder-skopeo-umoci
spec:
  template:
    metadata:
      annotations:
        guix-default-channel-commit: 5ed46735
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube1
