protocol bgp antifilter1 from dnpeers {
      # My side Tunnel IPv4
      local 192.168.0.175;
      ipv4 {
         next hop address 192.168.0.175;
      };
      # https://antifilter.network Side IPv4 and AS-Number
      neighbor 45.154.73.71 as 65432;
      hold time 240;
      multihop;
}
