protocol bgp antifilter0 from dnpeers {
      # My side Tunnel IPv4
      local 192.168.0.175;
      ipv4 {
         next hop address 192.168.0.175;
      };
      # https://antifilter.network Side IPv4 and AS-Number
      neighbor 45.148.244.55 as 65444;
      hold time 240;
      multihop;
}
