protocol bgp nixosworkstation {
      local as OWNAS;
      path metric 1;
      local 192.168.0.175;
      ipv4 {
         next hop self;
         import none;
         export all;
         # export filter { if (net = 162.159.134.0/23 || net = 162.159.128.0/23) then reject; accept; };
      };
      neighbor 192.168.0.195 as 64998;
}
