# protocol bgp wugi0 from localpeers {
#       # My side Tunnel IPv4
#       local 192.168.26.2;
#       ipv4 {
#          next hop address 192.168.26.2;
#       };
#       # https://antifilter.network Side IPv4 and AS-Number
#       neighbor 192.168.26.1 as 64999;
#       hold time 240;
#       multihop;
# }
