#!/run/current-system/profile/bin/guile \
--no-auto-compile -e (guile-nsenter) -s
!#

;;;; guile-nsenter --- Run nsenter
;;;; Copyright © 2025 Oleg Pykhalov <go.wigust@gmail.com>
;;;; Released under the GNU GPLv3 or any later version.

(define-module (guile-nsenter)
  #:use-module (srfi srfi-37)
  #:export (main))

;;; Commentary:
;;;
;;; DESCRIPTION
;;;
;;; Code:

(define %options
  (let ((display-and-exit-proc (lambda (msg)
                                 (lambda (opt name arg loads)
                                   (display msg) (quit)))))
    (list (option '(#\v "version") #f #f
                  (display-and-exit-proc "guile-nsenter version 0.0.1\n"))
          (option '(#\h "help") #f #f
                  (display-and-exit-proc
                   "Usage: guile-nsenter ...")))))

(define %default-options
  '())

(define (guile-with-environment expression)
  `(let* ((user (getpw (getuid)))
          (name (passwd:name user))
          (shell (passwd:shell user)))
     (execl shell shell "--login" "-c"
            (with-output-to-string
              (lambda ()
                (write
                 (list
                  "/run/current-system/profile/bin/guile" "--no-auto-compile"
                  "-c" ,(with-output-to-string
                          (lambda ()
                            (write expression))))))))))

(define %git-origin
  "https://cgit.wugi.info/git/wigust/dotfiles")

(define (runc-code)
  `(begin
     (define (git . args)
       (apply system* (append '("guix" "shell" "git" "--" "git") args)))
     (and=> (getenv "HOME")
            (lambda (home)
              (let ((commit (getenv "GIT_COMMIT"))
                    (workdir
                     (mkdtemp
                      (string-append
                       home "/.cache/wigust/checkouts/dotfiles.XXXXXXXXXX"))))
                (chdir workdir)
                (and
                 (zero? (git "init"))
                 (zero?
                  (git "remote" "add" "origin" ,%git-origin))
                 (zero?
                  (git "fetch" "--depth" (number->string 1) "origin" commit))
                 (zero? (git "checkout" commit))
                 ;; TODO: Do not copy openssh.scm from other location.
                 (copy-file (string-append home "/openssh.scm")
                            "wugi/home/config/openssh.scm")
                 ;; TODO: Do not copy intr.json from other location.
                 (system* "mkdir" "-p" "wugi/etc/mjru")
                 (copy-file (string-append home "/intr.json")
                            "wugi/etc/mjru/intr.json")
                 (zero? (system* "guix" "shell" "git" "make" "skopeo" "--"
                                 "make" (getenv "RUNC_MAKE_TARGET")))))))))

(define kubectl
  "/home/oleg/.guix-profile")

(define kubeconfig
  "/home/oleg/.kube/config")

(define (kubectl-program)
  ;; TODO: Use Kubernetes HTTP API without kubectl.
  `(begin
     (setenv "KUBECONFIG" ,kubeconfig)
     (system* ,(string-append kubectl "/bin/kubectl")
              (string-append "--namespace=" (getenv "KUBERNETES_NAMESPACE"))
              "exec" "--stdin=true"
              (string-append "pod/" (getenv "RUNC_CONTAINER_ID")) "--"
              "runc" "exec"
              "--user" (string-append
                        (getenv "RUNC_UID") ":" (getenv "RUNC_GID"))
              "--env" (string-append "GIT_COMMIT=" (getenv "GIT_COMMIT"))
              "--env" (string-append "RUNC_MAKE_TARGET="
                                     (getenv "RUNC_MAKE_TARGET"))
              "guix-builder"
              "/run/current-system/profile/bin/guile" "--no-auto-compile"
              "-c" ,(with-output-to-string
                      (lambda ()
                        (write
                         (guile-with-environment (runc-code))))))))

(define (main args)
  (define opts
    (args-fold (cdr (program-arguments))
               %options
               (lambda (opt name arg loads)
                 (error "Unrecognized option `~A'" name))
               (lambda (op loads)
                 (cons op loads))
               %default-options))
  (apply system*
         `("nsenter"
           ,(string-append "--target=" (number->string 1))
           "--mount"
           "--uts"
           "--ipc"
           "--net"
           "--pid"
           "--no-fork"
           ,@(or (and=> (getenv "NSENTER_UID")
                        (lambda (uid)
                          (list (string-append "--setuid=" uid))))
                 '())
           ,@(or (and=> (getenv "NSENTER_GID")
                        (lambda (gid)
                          (list (string-append "--setgid=" gid))))
                 '())
           "/usr/bin/env"
           ,(string-append "GIT_COMMIT=" (getenv "GIT_COMMIT"))
           ,(string-append "RUNC_CONTAINER_ID=" (getenv "RUNC_CONTAINER_ID"))
           ,(string-append "KUBERNETES_NAMESPACE="
                           (getenv "KUBERNETES_NAMESPACE"))
           ,@(or (and=> (getenv "RUNC_UID")
                        (lambda (uid)
                          (list (string-append "RUNC_UID=" uid))))
                 '())
           ,@(or (and=> (getenv "RUNC_GID")
                        (lambda (gid)
                          (list (string-append "RUNC_GID=" gid))))
                 '())
           ,@(or (and=> (getenv "RUNC_MAKE_TARGET")
                        (lambda (make-target)
                          (list
                           (string-append "RUNC_MAKE_TARGET=" make-target))))
                 '())
           "/run/current-system/profile/bin/guile" "--no-auto-compile"
           "-c" ,(with-output-to-string (lambda () (write (kubectl-program)))))))

;;; guile-nsenter ends here
