---
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  bgpInstances:
  - name: "instance-64981"
    localASN: 64981
    peers:
    - name: "tor-switch"
      peerASN: 64983
      peerAddress: 192.168.0.110
      peerConfigRef:
        name: "cilium-peer"
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: cilium-peer
spec:
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
  - afi: ipv4
    safi: unicast
    advertisements:
      matchLabels:
        advertise: "bgp"
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-advertisements
  labels:
    advertise: bgp
spec:
  advertisements:
  - advertisementType: "PodCIDR"
    attributes:
      communities:
        standard: [ "64981:99" ]
  - advertisementType: "Service"
    attributes:
      communities:
        standard: [ "64981:100" ]
    selector:
      matchLabels:
        app.kubernetes.io/name: ingress-nginx
    service:
      addresses:
      - LoadBalancerIP
